# Management config for PagerDuty.
##
# This is not currently automated by Github Actions and is mostly meant to make setup faster
# for new projects or PagerDuty accounts.
#

# This key was generated by Kevin Yeh on 10-21-2020 and should be replaced if he leaves.
# This was manually stored in SSM and are not managed through Terraform.
# 
data "aws_ssm_parameter" "pagerduty_api_key" {
  name = "/admin/common/pagerduty-api-key"
}

provider "aws" {
  region = "us-east-1"
  alias  = "us-east-1"
}

provider "newrelic" {
  region        = "US"
  account_id    = "2837112"
  api_key       = data.aws_ssm_parameter.newrelic-api-key.value
  admin_api_key = data.aws_ssm_parameter.newrelic-admin-api-key.value
}

terraform {
  required_version = "0.14.7"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.74.1"
    }
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.30.0"
    }
    pagerduty = {
      source  = "pagerduty/pagerduty"
      version = "~> 2.0.0"
    }
  }

  backend "s3" {
    bucket         = "massgov-pfml-aws-account-mgmt"
    key            = "terraform/monitoring.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform_locks"
    encrypt        = "true"
  }
}

provider "pagerduty" {
  token = data.aws_ssm_parameter.pagerduty_api_key.value
}

module "constants" {
  source = "../constants"
}

# Defined in pfml-aws/kms.tf
# All SNS topics defined in monitoring directory will need to use this key
# This key is not restricted by any environment
data "aws_kms_key" "main_kms_key" {
  key_id = "alias/massgov-pfml-main-kms-key"
}
