## include template file
include ../Makefile.template

## Build and release variables

API_DIR := $(realpath ../..)
API_DIST_DIR := $(API_DIR)/dist
LAMBDA_FUNCTION_NAME := CognitoPreSignup
LAMBDA_BUILD_BUCKET := massgov-pfml-api-lambda-builds
LAMBDA_BUILD_PREFIX := cognito-pre-signup
LOCAL_INVOKE_EVENT_JSON := test_event.json
