## include template file
include ../../Makefile.template

## Build and release variables

API_DIR := $(realpath ../../..)
API_DIST_DIR := $(API_DIR)/dist
LAMBDA_FUNCTION_NAME := EligibilityExportFunction
LAMBDA_BUILD_BUCKET := massgov-pfml-api-lambda-builds
LAMBDA_BUILD_PREFIX := fineos-eligibility-feed-export