AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Mass PFML - Export Eligibility Feed to Fineos

Globals:
  Function:
    Timeout: 900

Resources:
  EligibilityExportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: handler.handler
      Runtime: python3.8
      Environment:
        Variables:
          ENVIRONMENT: "SET_IN_CONTAINER_ENV_VARS"
          EXPORT_FOLDER_PATH: "SET_IN_LOCAL_ENV_VARS"          
          DB_HOST: "SET_IN_CONTAINER_ENV_VARS"
          DB_NAME: "SET_IN_CONTAINER_ENV_VARS"
          DB_USERNAME: "SET_IN_CONTAINER_ENV_VARS"
          DB_PASSWORD: "SET_IN_CONTAINER_ENV_VARS"
