AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Mass PFML - Export Eligibility Feed to Fineos

Globals:
  Function:
    Timeout: 900

Resources:
  EligibilityExportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../../massgov/pfml/fineos/eligibility_feed_export/
      Handler: eligibility_export.handler
      Runtime: python3.8
      Layers:
        - !Ref DependenciesLayer
      Environment:
        Variables:
          EXPORT_FOLDER_PATH: "SET_IN_LOCAL_ENV_VARS"
          DB_HOST: "SET_IN_CONTAINER_ENV_VARS"
          DB_NAME: "SET_IN_CONTAINER_ENV_VARS"
          DB_USERNAME: "SET_IN_CONTAINER_ENV_VARS"
          DB_PASSWORD: "SET_IN_CONTAINER_ENV_VARS"          
          DECRYPT: "SET_IN_CONTAINER_ENV_VARS"
          GPG_DECRYPTION_KEY_SSM_PATH: "SET_IN_CONTAINER_ENV_VARS"
          GPG_DECRYPTION_KEY_PASSPHRASE_SSM_PATH: "SET_IN_CONTAINER_ENV_VARS"
          LD_LIBRARY_PATH: "SET_IN_LOCAL_ENV_VARS"
          PATH: "SET_IN_LOCAL_ENV_VARS"

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies.zip
