AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mass PFML - Import Department of Revenue Data

Globals:
  Function:
    Timeout: 900

Resources:
  ImportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../massgov/pfml/data_integrations/dor/import/lambda/
      Handler: import_dor.handler
      Runtime: python3.8
      Layers:
        - !Ref DependenciesLayer
      Environment:
        Variables:
          DB_HOST: "SET_IN_CONTAINER_ENV_VARS"
          DB_NAME: "SET_IN_CONTAINER_ENV_VARS"
          DB_USERNAME: "SET_IN_CONTAINER_ENV_VARS"
          DB_PASSWORD: "SET_IN_CONTAINER_ENV_VARS"
          DECRYPT: "SET_IN_CONTAINER_ENV_VARS"
          GPG_DECRYPTION_KEY_SSM_PATH: "SET_IN_CONTAINER_ENV_VARS"
          GPG_DECRYPTION_KEY_PASSPHRASE_SSM_PATH: "SET_IN_CONTAINER_ENV_VARS"
          LD_LIBRARY_PATH: "SET_IN_LOCAL_ENV_VARS"
          PATH: "SET_IN_LOCAL_ENV_VARS"

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies.zip
