# Management config for PagerDuty.
#
# This is not currently automated by Github Actions and is mostly meant to make setup faster
# for new projects or PagerDuty accounts.
#

# This key was generated by Kevin Yeh on 10-21-2020 and should be replaced if he leaves.
# This was manually stored in SSM and are not managed through Terraform.
# 
data "aws_ssm_parameter" "pagerduty_api_key" {
  name = "/admin/common/pagerduty-api-key"
}

terraform {
  required_version = "0.12.24"

  backend "s3" {
    bucket         = "massgov-pfml-aws-account-mgmt"
    key            = "terraform/pagerduty.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform_locks"
    encrypt        = "true"
  }
}

provider "pagerduty" {
  token = data.aws_ssm_parameter.pagerduty_api_key.value
}
