resource "aws_cloudwatch_log_group" "gateway_execution_log_group" {
  # Has to be exactly this name to match what would have been autogenerated by AWS.
  name              = "API-Gateway-Execution-Logs_${aws_api_gateway_rest_api.pfml.id}/${var.environment_name}"
  retention_in_days = 7
}

resource "aws_cloudwatch_log_subscription_filter" "gateway_execution_logs_to_newrelic" {
  name            = "gateway_execution_logs_to_newrelic"
  log_group_name  = aws_cloudwatch_log_group.gateway_execution_log_group.name
  destination_arn = module.constants.newrelic_log_ingestion_arn
  # matches all log events
  filter_pattern = ""
}

# Allows the newrelic log ingestion lambda to retrieve its telemetry from any and all CloudWatch log groups.
resource "aws_lambda_permission" "nr_lambda_permission_generic" {
  statement_id  = "NRLambdaPermission_AnyLogGroup"
  action        = "lambda:InvokeFunction"
  principal     = "logs.us-east-1.amazonaws.com"
  function_name = module.constants.newrelic_log_ingestion_arn
  source_arn    = "arn:aws:logs:us-east-1:498823821309:log-group:*:*"
}
