"""Add date and counter columns to ctr_document_identifier

Revision ID: bde264ac357c
Revises: bef7e8d6100b
Create Date: 2020-12-23 23:33:29.162909

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bde264ac357c"
down_revision = "bef7e8d6100b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ctr_document_identifier", sa.Column("document_counter", sa.Integer(), nullable=False)
    )
    op.add_column("ctr_document_identifier", sa.Column("document_date", sa.Date(), nullable=False))
    op.create_index(
        op.f("ix_ctr_document_identifier_document_counter"),
        "ctr_document_identifier",
        ["document_counter"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctr_document_identifier_document_date"),
        "ctr_document_identifier",
        ["document_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ctr_document_identifier_document_date"), table_name="ctr_document_identifier"
    )
    op.drop_index(
        op.f("ix_ctr_document_identifier_document_counter"), table_name="ctr_document_identifier"
    )
    op.drop_column("ctr_document_identifier", "document_date")
    op.drop_column("ctr_document_identifier", "document_counter")
    # ### end Alembic commands ###
