"""add application_id to document

Revision ID: b1b0ff11c961
Revises: 318c5159a185
Create Date: 2020-09-03 16:56:30.067719

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b1b0ff11c961"
down_revision = "e570ea21490f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document", sa.Column("application_id", postgresql.UUID(as_uuid=True), nullable=False)
    )
    op.create_foreign_key(
        "fk_document_application_id",
        "document",
        "application",
        ["application_id"],
        ["application_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_document_application_id", "document", type_="foreignkey")
    op.drop_column("document", "application_id")
    # ### end Alembic commands ###
