"""Create work pattern models

Revision ID: 96f83ba34132
Revises: 45794436686c
Create Date: 2020-10-20 23:11:38.453517

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "96f83ba34132"
down_revision = "45794436686c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_day_of_week",
        sa.Column("day_of_week_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("day_of_week_description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("day_of_week_id"),
    )
    op.create_table(
        "lk_work_pattern_type",
        sa.Column("work_pattern_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("work_pattern_type_description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("work_pattern_type_id"),
    )
    op.create_table(
        "work_pattern",
        sa.Column("work_pattern_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("work_pattern_type_id", sa.Integer(), nullable=True),
        sa.Column("work_week_starts_id", sa.Integer(), nullable=True),
        sa.Column("pattern_start_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["work_pattern_type_id"], ["lk_work_pattern_type.work_pattern_type_id"]
        ),
        sa.ForeignKeyConstraint(["work_week_starts_id"], ["lk_day_of_week.day_of_week_id"]),
        sa.PrimaryKeyConstraint("work_pattern_id"),
    )
    op.create_table(
        "work_pattern_day",
        sa.Column("work_pattern_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("day_of_week_id", sa.Integer(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=False),
        sa.Column("hours", sa.Integer(), nullable=True),
        sa.Column("minutes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["day_of_week_id"], ["lk_day_of_week.day_of_week_id"]),
        sa.ForeignKeyConstraint(["work_pattern_id"], ["work_pattern.work_pattern_id"]),
        sa.PrimaryKeyConstraint("work_pattern_id", "day_of_week_id", "week_number"),
    )
    op.add_column(
        "application", sa.Column("work_pattern_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.create_foreign_key(
        None, "application", "work_pattern", ["work_pattern_id"], ["work_pattern_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "work_pattern_id")
    op.drop_table("work_pattern_day")
    op.drop_table("work_pattern")
    op.drop_table("lk_work_pattern_type")
    op.drop_table("lk_day_of_week")
    # ### end Alembic commands ###
