"""Add unique constraint to user.active_directory_id column

Revision ID: ac77dfa6613a
Revises: ade657166cb1
Create Date: 2020-10-28 13:28:05.257938

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "ac77dfa6613a"
down_revision = "ade657166cb1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_active_directory_id", table_name="user")
    op.create_index(
        op.f("ix_user_active_directory_id"), "user", ["active_directory_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_active_directory_id"), table_name="user")
    op.create_index("ix_user_active_directory_id", "user", ["active_directory_id"], unique=False)
    # ### end Alembic commands ###
