"""Add column to employment_status table for FINEOS labels

Revision ID: d76999cd21ff
Revises: 1e28741cdbd3
Create Date: 2020-11-30 18:56:52.537471

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d76999cd21ff"
down_revision = "1e28741cdbd3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lk_employment_status", sa.Column("fineos_label", sa.Text()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lk_employment_status", "fineos_label")
    # ### end Alembic commands ###
