"""add unique contraint to active_directory_id in USER table

Revision ID: 60602f834ba5
Revises: f1720ed9d6e6
Create Date: 2020-10-14 18:37:29.092183

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "60602f834ba5"
down_revision = "f1720ed9d6e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user", ["active_directory_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    # ### end Alembic commands ###
