"""Index tax identifier ID on application

Revision ID: 4a77e100b58c
Revises: 0b9b1fffb167
Create Date: 2020-11-20 15:39:11.047105

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "4a77e100b58c"
down_revision = "0b9b1fffb167"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_application_tax_identifier_id"), "application", ["tax_identifier_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_application_tax_identifier_id"), table_name="application")
    # ### end Alembic commands ###
