"""Create PreviousLeave and PreviousLeaveQualifyingReason

Revision ID: f1d2e7bf289b
Revises: 627e0dbd79c7
Create Date: 2020-12-11 21:20:46.468084

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f1d2e7bf289b"
down_revision = "627e0dbd79c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_previous_leave_qualifying_reason",
        sa.Column(
            "previous_leave_qualifying_reason_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("previous_leave_qualifying_reason_description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("previous_leave_qualifying_reason_id"),
    )
    op.create_table(
        "previous_leave",
        sa.Column("previous_leave_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("application_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("leave_start_date", sa.Date(), nullable=True),
        sa.Column("leave_end_date", sa.Date(), nullable=True),
        sa.Column("is_for_current_employer", sa.Boolean(), nullable=True),
        sa.Column("leave_reason_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["application_id"], ["application.application_id"]),
        sa.ForeignKeyConstraint(
            ["leave_reason_id"],
            ["lk_previous_leave_qualifying_reason.previous_leave_qualifying_reason_id"],
        ),
        sa.PrimaryKeyConstraint("previous_leave_id"),
    )
    op.create_index(
        op.f("ix_previous_leave_application_id"), "previous_leave", ["application_id"], unique=False
    )
    op.add_column("application", sa.Column("has_previous_leaves", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "has_previous_leaves")
    op.drop_index(op.f("ix_previous_leave_application_id"), table_name="previous_leave")
    op.drop_table("previous_leave")
    op.drop_table("lk_previous_leave_qualifying_reason")
    # ### end Alembic commands ###
