"""Add log tables for employer and employee models

Revision ID: aee3c2d906fb
Revises: 37f1504f1b9f
Create Date: 2020-09-30 15:18:12.771459

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aee3c2d906fb"
down_revision = "6e3cbf909149"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_log",
        sa.Column("employee_log_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("employee_log_id"),
    )
    op.create_index(op.f("ix_employee_log_action"), "employee_log", ["action"], unique=False)
    op.create_index(
        op.f("ix_employee_log_employee_id"), "employee_log", ["employee_id"], unique=False
    )
    op.create_table(
        "employer_log",
        sa.Column("employer_log_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("employer_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("employer_log_id"),
    )
    op.create_index(op.f("ix_employer_log_action"), "employer_log", ["action"], unique=False)
    op.create_index(
        op.f("ix_employer_log_employer_id"), "employer_log", ["employer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employer_log_employer_id"), table_name="employer_log")
    op.drop_index(op.f("ix_employer_log_action"), table_name="employer_log")
    op.drop_table("employer_log")
    op.drop_index(op.f("ix_employee_log_employee_id"), table_name="employee_log")
    op.drop_index(op.f("ix_employee_log_action"), table_name="employee_log")
    op.drop_table("employee_log")
    # ### end Alembic commands ###
