"""API-972: Add payment method to employee

Revision ID: 59343011b60c
Revises: 521da22e3f61
Create Date: 2020-12-15 18:15:08.709367

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "59343011b60c"
down_revision = "521da22e3f61"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employee", sa.Column("payment_method_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "employee_payment_method_id_fkey",
        "employee",
        "lk_payment_method",
        ["payment_method_id"],
        ["payment_method_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("employee_payment_method_id_fkey", "employee", type_="foreignkey")
    op.drop_column("employee", "payment_method_id")
    # ### end Alembic commands ###
