"""employer name account key exemption

Revision ID: 8d5f436b37e9
Revises: 88d2159c082c
Create Date: 2020-04-28 16:42:29.938398

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8d5f436b37e9"
down_revision = "a5a12d592f91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employer", sa.Column("dor_updated_date", sa.Date(), nullable=True))
    op.add_column("employer", sa.Column("exemption_cease_date", sa.Date(), nullable=True))
    op.add_column("employer", sa.Column("exemption_commence_date", sa.Date(), nullable=True))
    op.add_column("employer", sa.Column("family_exemption", sa.Boolean(), nullable=True))
    op.add_column("employer", sa.Column("medical_exemption", sa.Boolean(), nullable=True))
    op.add_column("employer", sa.Column("account_key", sa.Text(), nullable=True))
    op.add_column("employer", sa.Column("employer_name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employer", "employer_name")
    op.drop_column("employer", "account_key")
    op.drop_column("employer", "medical_exemption")
    op.drop_column("employer", "family_exemption")
    op.drop_column("employer", "exemption_commence_date")
    op.drop_column("employer", "exemption_cease_date")
    op.drop_column("employer", "dor_updated_date")
    # ### end Alembic commands ###
