"""add fineos_absence_id to claim table

Revision ID: 1e28741cdbd3
Revises: a33179b41e77
Create Date: 2020-11-25 16:58:17.868257

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e28741cdbd3"
down_revision = "8e819984d058"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("claim", sa.Column("fineos_absence_id", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_claim_fineos_absence_id"), "claim", ["fineos_absence_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_claim_fineos_absence_id"), table_name="claim")
    op.drop_column("claim", "fineos_absence_id")
    # ### end Alembic commands ###
