"""Create various column indexes

Revision ID: 3c7f53532558
Revises: 81e8a877901e
Create Date: 2020-10-27 10:01:57.828508

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c7f53532558"
down_revision = "81e8a877901e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_application_employee_id"), "application", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_application_employer_id"), "application", ["employer_id"], unique=False
    )
    op.create_index(
        op.f("ix_application_fineos_absence_id"), "application", ["fineos_absence_id"], unique=False
    )
    op.create_index(
        op.f("ix_application_fineos_notification_case_id"),
        "application",
        ["fineos_notification_case_id"],
        unique=False,
    )
    op.create_index(op.f("ix_application_user_id"), "application", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_application_payment_preference_application_id"),
        "application_payment_preference",
        ["application_id"],
        unique=False,
    )
    op.create_index(op.f("ix_claim_employer_id"), "claim", ["employer_id"], unique=False)
    op.create_index(
        op.f("ix_continuous_leave_period_application_id"),
        "continuous_leave_period",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_application_id"), "document", ["application_id"], unique=False
    )
    op.create_index(op.f("ix_document_user_id"), "document", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_employee_latest_import_log_id"), "employee", ["latest_import_log_id"], unique=False
    )
    op.create_index(
        op.f("ix_employee_tax_identifier_id"), "employee", ["tax_identifier_id"], unique=False
    )
    op.create_index(op.f("ix_employer_account_key"), "employer", ["account_key"], unique=False)
    op.create_index(op.f("ix_employer_employer_fein"), "employer", ["employer_fein"], unique=False)
    op.create_index(
        op.f("ix_employer_fineos_customer_nbr"), "employer", ["fineos_customer_nbr"], unique=False
    )
    op.create_index(
        op.f("ix_employer_fineos_employer_id"), "employer", ["fineos_employer_id"], unique=False
    )
    op.create_index(
        op.f("ix_employer_latest_import_log_id"), "employer", ["latest_import_log_id"], unique=False
    )
    op.create_index(op.f("ix_import_log_import_type"), "import_log", ["import_type"], unique=False)
    op.create_index(op.f("ix_import_log_source"), "import_log", ["source"], unique=False)
    op.create_index(op.f("ix_import_log_start"), "import_log", ["start"], unique=False)
    op.create_index(
        op.f("ix_intermittent_leave_period_application_id"),
        "intermittent_leave_period",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reduced_schedule_leave_period_application_id"),
        "reduced_schedule_leave_period",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rmv_check_absence_case_id"), "rmv_check", ["absence_case_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_active_directory_id"), "user", ["active_directory_id"], unique=False
    )
    op.create_index(
        op.f("ix_wages_and_contributions_employee_id"),
        "wages_and_contributions",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wages_and_contributions_employer_id"),
        "wages_and_contributions",
        ["employer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wages_and_contributions_filing_period"),
        "wages_and_contributions",
        ["filing_period"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wages_and_contributions_latest_import_log_id"),
        "wages_and_contributions",
        ["latest_import_log_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wages_and_contributions_latest_import_log_id"),
        table_name="wages_and_contributions",
    )
    op.drop_index(
        op.f("ix_wages_and_contributions_filing_period"), table_name="wages_and_contributions"
    )
    op.drop_index(
        op.f("ix_wages_and_contributions_employer_id"), table_name="wages_and_contributions"
    )
    op.drop_index(
        op.f("ix_wages_and_contributions_employee_id"), table_name="wages_and_contributions"
    )
    op.drop_index(op.f("ix_user_active_directory_id"), table_name="user")
    op.drop_index(op.f("ix_rmv_check_absence_case_id"), table_name="rmv_check")
    op.drop_index(
        op.f("ix_reduced_schedule_leave_period_application_id"),
        table_name="reduced_schedule_leave_period",
    )
    op.drop_index(
        op.f("ix_intermittent_leave_period_application_id"), table_name="intermittent_leave_period"
    )
    op.drop_index(op.f("ix_import_log_start"), table_name="import_log")
    op.drop_index(op.f("ix_import_log_source"), table_name="import_log")
    op.drop_index(op.f("ix_import_log_import_type"), table_name="import_log")
    op.drop_index(op.f("ix_employer_latest_import_log_id"), table_name="employer")
    op.drop_index(op.f("ix_employer_fineos_employer_id"), table_name="employer")
    op.drop_index(op.f("ix_employer_fineos_customer_nbr"), table_name="employer")
    op.drop_index(op.f("ix_employer_employer_fein"), table_name="employer")
    op.drop_index(op.f("ix_employer_account_key"), table_name="employer")
    op.drop_index(op.f("ix_employee_tax_identifier_id"), table_name="employee")
    op.drop_index(op.f("ix_employee_latest_import_log_id"), table_name="employee")
    op.drop_index(op.f("ix_document_user_id"), table_name="document")
    op.drop_index(op.f("ix_document_application_id"), table_name="document")
    op.drop_index(
        op.f("ix_continuous_leave_period_application_id"), table_name="continuous_leave_period"
    )
    op.drop_index(op.f("ix_claim_employer_id"), table_name="claim")
    op.drop_index(
        op.f("ix_application_payment_preference_application_id"),
        table_name="application_payment_preference",
    )
    op.drop_index(op.f("ix_application_user_id"), table_name="application")
    op.drop_index(op.f("ix_application_fineos_notification_case_id"), table_name="application")
    op.drop_index(op.f("ix_application_fineos_absence_id"), table_name="application")
    op.drop_index(op.f("ix_application_employer_id"), table_name="application")
    op.drop_index(op.f("ix_application_employee_id"), table_name="application")
    # ### end Alembic commands ###
