"""change name of wage_and_contribution_id table

Revision ID: 79e1405a1b3e
Revises: 066044391b6f
Create Date: 2020-05-11 16:11:38.253391

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "79e1405a1b3e"
down_revision = "066044391b6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("wage_and_contribution_id", "wages_and_contributions")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("wages_and_contributions", "wage_and_contribution_id")
    # ### end Alembic commands ###
