"""Remove lk_status table

Revision ID: 31d78e6fcd24
Revises: ccb45b4c0238
Create Date: 2020-06-10 21:38:26.034930

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "31d78e6fcd24"
down_revision = "ccb45b4c0238"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("application_status_fkey", "application", type_="foreignkey")
    op.drop_column("application", "status_id")
    op.drop_constraint(
        "continuous_leave_period_status_fkey", "continuous_leave_period", type_="foreignkey"
    )
    op.drop_column("continuous_leave_period", "status_id")
    op.drop_constraint(
        "reduced_schedule_leave_period_status_fkey",
        "reduced_schedule_leave_period",
        type_="foreignkey",
    )
    op.drop_column("reduced_schedule_leave_period", "status_id")
    op.drop_table("lk_status")
    op.add_column(
        "continuous_leave_period",
        sa.Column("is_estimated", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        "reduced_schedule_leave_period",
        sa.Column("is_estimated", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_status",
        sa.Column("status_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("status_description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("status_id", name="lk_status_pkey"),
    )
    op.add_column(
        "reduced_schedule_leave_period",
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "reduced_schedule_leave_period_status_fkey",
        "reduced_schedule_leave_period",
        "lk_status",
        ["status_id"],
        ["status_id"],
    )
    op.add_column(
        "continuous_leave_period",
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "continuous_leave_period_status_fkey",
        "continuous_leave_period",
        "lk_status",
        ["status_id"],
        ["status_id"],
    )
    op.add_column(
        "application", sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "application_status_fkey", "application", "lk_status", ["status_id"], ["status_id"]
    )
    op.drop_column("reduced_schedule_leave_period", "is_estimated")
    op.drop_column("continuous_leave_period", "is_estimated")
    # ### end Alembic commands ###
