"""API-1144: Remove payment method ID from payment

Revision ID: a1f73214064c
Revises: d6d53b34006c
Create Date: 2020-12-30 00:31:49.811045

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1f73214064c"
down_revision = "d6d53b34006c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("payment_payment_method_id_fkey", "payment", type_="foreignkey")
    op.drop_column("payment", "payment_method_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment", sa.Column("payment_method_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        "payment_payment_method_id_fkey",
        "payment",
        "lk_payment_method",
        ["payment_method_id"],
        ["payment_method_id"],
    )
    # ### end Alembic commands ###
