"""add employment_status to applications

Revision ID: 837b1109d1aa
Revises: 22386a328e20
Create Date: 2020-07-13 10:49:02.252281

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "837b1109d1aa"
down_revision = "22386a328e20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_employment_status",
        sa.Column("employment_status_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employment_status_description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("employment_status_id"),
    )
    op.add_column("application", sa.Column("employment_status_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "application",
        "lk_employment_status",
        ["employment_status_id"],
        ["employment_status_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "application", type_="foreignkey")
    op.drop_column("application", "employment_status_id")
    op.drop_table("lk_employment_status")
    # ### end Alembic commands ###
