"""Drop employer.fineos_customer_nbr

Revision ID: 3267f0d49aed
Revises: a32c996ececb
Create Date: 2020-11-12 15:57:53.817633

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3267f0d49aed"
down_revision = "a32c996ececb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_employer_fineos_customer_nbr", table_name="employer")
    op.drop_column("employer", "fineos_customer_nbr")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employer", sa.Column("fineos_customer_nbr", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index(
        "ix_employer_fineos_customer_nbr", "employer", ["fineos_customer_nbr"], unique=False
    )
    # ### end Alembic commands ###
