"""Add leave period has_ boolean fields for Portal UI

Revision ID: 7115fde34652
Revises: a11308cbf969
Create Date: 2020-09-28 15:27:09.873356

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7115fde34652"
down_revision = "349d151adab3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application", sa.Column("has_continuous_leave_periods", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "application", sa.Column("has_intermittent_leave_periods", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "application", sa.Column("has_reduced_schedule_leave_periods", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "has_reduced_schedule_leave_periods")
    op.drop_column("application", "has_intermittent_leave_periods")
    op.drop_column("application", "has_continuous_leave_periods")
    # ### end Alembic commands ###
