"""Add import log table

Revision ID: de11a2e7af43
Revises: c55f558a528e
Create Date: 2020-05-01 13:57:39.034682

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de11a2e7af43"
down_revision = "c55f558a528e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_log",
        sa.Column("import_log_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("import_type", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("report", sa.Text(), nullable=True),
        sa.Column("start", sa.DateTime(), nullable=True),
        sa.Column("end", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("import_log_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("import_log")
    # ### end Alembic commands ###
