"""Responding to feedback about Verifications

Revision ID: b6fb18dae123
Revises: 2a38e41f50b2
Create Date: 2020-08-27 00:55:07.888126

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b6fb18dae123"
down_revision = "2a38e41f50b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verification",
        sa.Column("verification_code_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.add_column(
        "verification", sa.Column("verified_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.create_foreign_key(
        None,
        "verification",
        "verification_code",
        ["verification_code_id"],
        ["verification_code_id"],
    )
    op.drop_column("verification", "related_id")
    op.drop_column("verification", "verification_ts")
    op.add_column(
        "verification_code", sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False)
    )
    op.add_column(
        "verification_code", sa.Column("issued_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.drop_column("verification_code", "issue_ts")
    op.drop_column("verification_code", "expiration_ts")
    op.add_column(
        "verification_code_log", sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.drop_column("verification_code_log", "log_ts")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verification_code_log",
        sa.Column(
            "log_ts", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("verification_code_log", "created_at")
    op.add_column(
        "verification_code",
        sa.Column(
            "expiration_ts",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "verification_code",
        sa.Column(
            "issue_ts", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("verification_code", "issued_at")
    op.drop_column("verification_code", "expires_at")
    op.add_column(
        "verification",
        sa.Column(
            "verification_ts",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "verification",
        sa.Column("related_id", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "verification", type_="foreignkey")
    op.drop_column("verification", "verified_at")
    op.drop_column("verification", "verification_code_id")
    # ### end Alembic commands ###
