"""Add date of birth to applications

Revision ID: 80603792e3a2
Revises: 22386a328e20
Create Date: 2020-07-15 12:25:12.983987

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "80603792e3a2"
down_revision = "22386a328e20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("application", sa.Column("date_of_birth", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "date_of_birth")
    # ### end Alembic commands ###
