"""Remove the related_role_id column from the UserRole table (API-503)

Revision ID: 2f571f16ffb6
Revises: 438401d159b6
Create Date: 2020-09-15 19:18:30.358872

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2f571f16ffb6"
down_revision = "438401d159b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("link_user_role", "related_role_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "link_user_role",
        sa.Column("related_role_id", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
