"""Add child_birth_date and child_placement_date fields.

Revision ID: 4535bd46fe78
Revises: 020d8108295a
Create Date: 2020-08-13 23:28:55.080057

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4535bd46fe78"
down_revision = "020d8108295a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("application", sa.Column("child_birth_date", sa.Date(), nullable=True))
    op.add_column("application", sa.Column("child_placement_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "child_placement_date")
    op.drop_column("application", "child_birth_date")
    # ### end Alembic commands ###
