"""Remove user status

Revision ID: ccb45b4c0238
Revises: 13e4d1158583
Create Date: 2020-06-08 17:13:36.232714

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ccb45b4c0238"
down_revision = "13e4d1158583"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_status_type_fkey", "user", type_="foreignkey")
    op.drop_column("user", "status_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        "user_status_type_fkey", "user", "lk_status", ["status_id"], ["status_id"]
    )
    # ### end Alembic commands ###
