"""add email to user

Revision ID: a5a12d592f91
Revises: 88d2159c082c
Create Date: 2020-04-23 17:48:08.916766

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5a12d592f91"
down_revision = "88d2159c082c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email_address", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "email_address")
    # ### end Alembic commands ###
