"""import log tracking for employee, employer, and wage data

Revision ID: 9f6ed69ecae6
Revises: ccb45b4c0238
Create Date: 2020-06-11 11:29:39.489670

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9f6ed69ecae6"
down_revision = "ccb45b4c0238"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employee", sa.Column("latest_import_log_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "employee", "import_log", ["latest_import_log_id"], ["import_log_id"]
    )
    op.add_column("employer", sa.Column("latest_import_log_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "employer", "import_log", ["latest_import_log_id"], ["import_log_id"]
    )
    op.add_column(
        "wages_and_contributions", sa.Column("latest_import_log_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "wages_and_contributions", "import_log", ["latest_import_log_id"], ["import_log_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wages_and_contributions", type_="foreignkey")
    op.drop_column("wages_and_contributions", "latest_import_log_id")
    op.drop_constraint(None, "employer", type_="foreignkey")
    op.drop_column("employer", "latest_import_log_id")
    op.drop_constraint(None, "employee", type_="foreignkey")
    op.drop_column("employee", "latest_import_log_id")
    # ### end Alembic commands ###
