"""change application middle initial to middle name

Revision ID: b695fa114a27
Revises: edd52ebb9d9e
Create Date: 2020-07-15 18:48:52.590159

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b695fa114a27"
down_revision = "edd52ebb9d9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "application", column_name="middle_initial", new_column_name="middle_name", nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("application", column_name="middle_name", new_column_name="middle_inital")
    # ### end Alembic commands ###
