"""non nullable fields added to wages and employers

Revision ID: 066044391b6f
Revises: e081304c01b0
Create Date: 2020-05-05 18:38:05.280657

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "066044391b6f"
down_revision = "e081304c01b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("employer", "employer_dba", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("employer", "employer_fein", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("employer", "employer_fein", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("employer", "employer_dba", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
