"""Remove state_metric_id column

Revision ID: 1391944caff2
Revises: e01223effa2b
Create Date: 2020-10-29 23:27:33.849615

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1391944caff2"
down_revision = "e01223effa2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("state_metric_effective_date_key", "state_metric", type_="unique")
    op.drop_column("state_metric", "state_metric_id")
    # ### end Alembic commands ###
    op.create_primary_key("state_metric_pkey", "state_metric", ["effective_date"])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "state_metric",
        sa.Column(
            "state_metric_id",
            postgresql.UUID(),
            autoincrement=False,
            nullable=False,
            server_default=sa.text("lpad((random() * 1e8)::int::text, 32, '0')::uuid"),
        ),
    )
    op.create_unique_constraint(
        "state_metric_effective_date_key", "state_metric", ["effective_date"]
    )
    # ### end Alembic commands ###
    op.drop_constraint("state_metric_pkey", "state_metric", type_="primary")
    op.create_primary_key("state_metric_pkey", "state_metric", ["state_metric_id"])
