"""Add columns to lk_state and lk_reference_file_type

Revision ID: 0fc984e8a78d
Revises: 52cc9b2b3e28
Create Date: 2020-12-23 04:25:26.564747

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0fc984e8a78d"
down_revision = "52cc9b2b3e28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lk_reference_file_type", sa.Column("num_files_in_set", sa.Integer(), nullable=True)
    )
    op.add_column("lk_state", sa.Column("flow_id", sa.Integer(), nullable=True))
    op.create_foreign_key("lk_state_flow_id_fkey", "lk_state", "lk_flow", ["flow_id"], ["flow_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("lk_state_flow_id_fkey", "lk_state", type_="foreignkey")
    op.drop_column("lk_state", "flow_id")
    op.drop_column("lk_reference_file_type", "num_files_in_set")
    # ### end Alembic commands ###
