"""Create Phone model and PhoneType lookup

Revision ID: a33179b41e77
Revises: 4a77e100b58c
Create Date: 2020-11-24 22:23:33.914686

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a33179b41e77"
down_revision = "4a77e100b58c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_phone_type",
        sa.Column("phone_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("phone_type_description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("phone_type_id"),
    )
    op.create_table(
        "phone",
        sa.Column("fineos_phone_id", sa.Integer(), nullable=True),
        sa.Column("phone_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("phone_number", sa.Text(), nullable=True),
        sa.Column("phone_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["phone_type_id"], ["lk_phone_type.phone_type_id"]),
        sa.PrimaryKeyConstraint("phone_id"),
    )
    op.add_column(
        "application", sa.Column("phone_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.create_foreign_key(None, "application", "phone", ["phone_id"], ["phone_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "application", type_="foreignkey")  # type: ignore
    op.drop_column("application", "phone_id")
    op.drop_table("phone")
    op.drop_table("lk_phone_type")
    # ### end Alembic commands ###
