"""add email addresses to Verifications model

Revision ID: 4cda7c05eb32
Revises: be7953b6b042
Create Date: 2020-09-23 18:34:00.848839

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4cda7c05eb32"
down_revision = "be7953b6b042"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("verification", sa.Column("email_address", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verification", "email_address")
    # ### end Alembic commands ###
