"""remove primary keys from user_leave_administrator table

Revision ID: 68ae7fa8050e
Revises: ac77dfa6613a
Create Date: 2020-11-03 17:54:26.647158

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "68ae7fa8050e"
down_revision = "ac77dfa6613a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE link_user_leave_administrator DROP CONSTRAINT link_user_leave_administrator_pkey"
    )
    op.add_column(
        "link_user_leave_administrator",
        sa.Column("user_leave_administrator_id", postgresql.UUID(as_uuid=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("link_user_leave_administrator", "user_leave_administrator_id")
    op.execute(
        "ALTER TABLE link_user_leave_administrator ADD CONSTRAINT link_user_leave_administrator_pkey PRIMARY KEY (user_id, employer_id)"
    )
    # ### end Alembic commands ###
