"""Adding new table for linking split payments.

Revision ID: 5721fd5becbd
Revises: 69f0b99fed2d
Create Date: 2021-10-07 17:11:35.590706

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5721fd5becbd"
down_revision = "69f0b99fed2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link_split_payment",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("payment_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("related_payment_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["payment_id"], ["payment.payment_id"],),
        sa.ForeignKeyConstraint(["related_payment_id"], ["payment.payment_id"],),
        sa.PrimaryKeyConstraint("payment_id", "related_payment_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("link_split_payment")
    # ### end Alembic commands ###
