"""PUB-73: Create PUB EFT tables

Revision ID: 8786af650425
Revises: 088a421d40da
Create Date: 2021-03-15 18:56:18.938797

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8786af650425"
down_revision = "088a421d40da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_prenote_state",
        sa.Column("prenote_state_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("prenote_state_description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("prenote_state_id"),
    )
    op.create_table(
        "pub_eft",
        sa.Column("pub_eft_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("routing_nbr", sa.Text(), nullable=False),
        sa.Column("account_nbr", sa.Text(), nullable=False),
        sa.Column("bank_account_type_id", sa.Integer(), nullable=False),
        sa.Column("prenote_state_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("prenote_response_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_account_type_id"], ["lk_bank_account_type.bank_account_type_id"]
        ),
        sa.ForeignKeyConstraint(["prenote_state_id"], ["lk_prenote_state.prenote_state_id"]),
        sa.PrimaryKeyConstraint("pub_eft_id"),
    )
    op.create_table(
        "link_employee_pub_eft_pair",
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("pub_eft_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.employee_id"]),
        sa.ForeignKeyConstraint(["pub_eft_id"], ["pub_eft.pub_eft_id"]),
        sa.PrimaryKeyConstraint("employee_id", "pub_eft_id"),
    )
    op.add_column("payment", sa.Column("pub_eft_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(
        "payment_pub_eft_fkey", "payment", "pub_eft", ["pub_eft_id"], ["pub_eft_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("payment_pub_eft_fkey", "payment", type_="foreignkey")
    op.drop_column("payment", "pub_eft_id")
    op.drop_table("link_employee_pub_eft_pair")
    op.drop_table("pub_eft")
    op.drop_table("lk_prenote_state")
    # ### end Alembic commands ###
