"""created fineos payment extract staging tables

Revision ID: 9c6bc7a3c1cb
Revises: 4fbf27a4c801
Create Date: 2021-03-09 19:51:38.393429

"""


# revision identifiers, used by Alembic.
revision = "9c6bc7a3c1cb"
down_revision = "4fbf27a4c801"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
