"""Adding foreign key for MMARS.

Revision ID: 952219694811
Revises: 84a75d6c3739
Create Date: 2021-11-04 15:07:16.849998

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "952219694811"
down_revision = "84a75d6c3739"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE pfml_1099_mmars_payment ALTER COLUMN mmars_payment_id TYPE UUID USING (LPAD(TO_HEX(mmars_payment_id), 32, '0')::uuid)"
    )
    op.create_index(
        op.f("ix_pfml_1099_mmars_payment_mmars_payment_id"),
        "pfml_1099_mmars_payment",
        ["mmars_payment_id"],
        unique=False,
    )
    op.create_foreign_key(
        "pfml_1099_mmars_payment_mmars_payment_id_fkey",
        "pfml_1099_mmars_payment",
        "mmars_payment_data",
        ["mmars_payment_id"],
        ["mmars_payment_data_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "pfml_1099_mmars_payment_mmars_payment_id_fkey",
        "pfml_1099_mmars_payment",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_pfml_1099_mmars_payment_mmars_payment_id"), table_name="pfml_1099_mmars_payment"
    )
    op.execute(
        "ALTER TABLE pfml_1099_mmars_payment ALTER COLUMN mmars_payment_id TYPE integer USING ('0'::integer)"
    )
    # ### end Alembic commands ###
