"""Add Base Period columns for Benefit Year

Revision ID: b16411cf6648
Revises: 62daadb5a349
Create Date: 2021-12-02 20:20:16.077412

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b16411cf6648"
down_revision = "62daadb5a349"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("benefit_year", sa.Column("base_period_start_date", sa.Date(), nullable=True))
    op.add_column("benefit_year", sa.Column("base_period_end_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("benefit_year", "base_period_end_date")
    op.drop_column("benefit_year", "base_period_start_date")
    # ### end Alembic commands ###
