"""Payment leave request decision

Revision ID: 7668b7d4580b
Revises: 27e8f899e06b
Create Date: 2021-04-21 18:31:51.139876

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7668b7d4580b"
down_revision = "27e8f899e06b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("leave_request_decision", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment", "leave_request_decision")
    # ### end Alembic commands ###
