"""PAY-109: Add cancel date to 1099 payment.

Revision ID: a50d3101c1f3
Revises: 59394f6a082a
Create Date: 2021-11-30 18:56:05.065797

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a50d3101c1f3"
down_revision = "59394f6a082a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pfml_1099_payment", sa.Column("cancel_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pfml_1099_payment", "cancel_date")
    # ### end Alembic commands ###
