"""Add unique constraint for user.email_address

Revision ID: 12017bbb31e1
Revises: 2f5ec3c27a6b
Create Date: 2021-06-21 16:16:20.631880

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "12017bbb31e1"
down_revision = "2f5ec3c27a6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uniq_user_email_address", "user", ["email_address"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uniq_user_email_address", "user", type_="unique")
    # ### end Alembic commands ###
