"""API-1970: Add multicolumn indexes for payment data fetching

Revision ID: 2f5ec3c27a6b
Revises: e0506a86aaca
Create Date: 2021-10-18 19:38:43.953900

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f5ec3c27a6b"
down_revision = "e0506a86aaca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_employee_feed_import_log_id_customerno",
        "fineos_extract_employee_feed",
        ["fineos_extract_import_log_id", "customerno"],
        unique=False,
    )
    op.create_index(
        "ix_payment_details_leaverequest_reference_file_id",
        "fineos_extract_vbi_requested_absence",
        ["fineos_extract_import_log_id", "leaverequest_id"],
        unique=False,
    )
    op.create_index(
        "ix_claim_details_c_i_reference_file_id",
        "fineos_extract_vpei_claim_details",
        ["fineos_extract_import_log_id", "peclassid", "peindexid"],
        unique=False,
    )
    op.create_index(
        "ix_payment_details_c_i_reference_file_id",
        "fineos_extract_vpei_payment_details",
        ["fineos_extract_import_log_id", "peclassid", "peindexid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_payment_details_c_i_reference_file_id", table_name="fineos_extract_vpei_payment_details"
    )
    op.drop_index(
        "ix_claim_details_c_i_reference_file_id", table_name="fineos_extract_vpei_claim_details"
    )
    op.drop_index(
        "ix_payment_details_leaverequest_reference_file_id",
        table_name="fineos_extract_vbi_requested_absence",
    )
    op.drop_index(
        "ix_employee_feed_import_log_id_customerno", table_name="fineos_extract_employee_feed"
    )
    # ### end Alembic commands ###
