"""make verification id not nullable

Revision ID: a113c523fedf
Revises: f179009904e7
Create Date: 2021-04-29 21:19:11.635827

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import column, table

from massgov.pfml.db.models.base import utc_timestamp_gen
from massgov.pfml.db.models.verifications import VerificationType  # noqa: F401

# revision identifiers, used by Alembic.
revision = "a113c523fedf"
down_revision = "f179009904e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    verification = table(
        "verification",
        column("verification_id", UUID),
        column("verification_type_id", sa.Integer),
        column("updated_at", sa.TIMESTAMP(timezone=True)),
    )

    current_ts = utc_timestamp_gen()
    op.execute(
        verification.update()
        .where(verification.c.verification_type_id == None)  # noqa: E711
        .values(
            {
                "verification_type_id": VerificationType.PFML_WITHHOLDING.verification_type_id,
                "updated_at": current_ts,
            }
        )
    )

    op.alter_column(
        "verification", "verification_type_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "verification", "verification_type_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
