"""Add gender to application table

Revision ID: 86db3c551ac6
Revises: 53730ae44d1c
Create Date: 2021-04-12 20:02:04.350269

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "86db3c551ac6"
down_revision = "53730ae44d1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("application", sa.Column("gender_id", sa.Integer(), nullable=True))
    op.create_foreign_key("application_gender_id_fkey", "application", "lk_gender", ["gender_id"], ["gender_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("application_gender_id_fkey", "application", type_="foreignkey")
    op.drop_column("application", "gender_id")
    # ### end Alembic commands ###
