"""PUB-72: Add PUB individual IDs

Revision ID: d7b1fc15fefe
Revises: 7a7f2607f99d
Create Date: 2021-03-18 17:05:06.937646

"""
from typing import cast

import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import CreateSequence, DropSequence, Sequence

# revision identifiers, used by Alembic.
revision = "d7b1fc15fefe"
down_revision = "7a7f2607f99d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(cast(str, Sequence("payment_individual_id_seq", start=1))))
    op.add_column(
        "payment",
        sa.Column(
            "pub_individual_id",
            sa.Integer(),
            server_default=sa.text("nextval('payment_individual_id_seq')"),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_payment_pub_individual_id"), "payment", ["pub_individual_id"], unique=False
    )
    op.execute(CreateSequence(cast(str, Sequence("pub_eft_individual_id_seq", start=1))))
    op.add_column(
        "pub_eft",
        sa.Column(
            "pub_individual_id",
            sa.Integer(),
            server_default=sa.text("nextval('pub_eft_individual_id_seq')"),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_pub_eft_pub_individual_id"), "pub_eft", ["pub_individual_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pub_eft_pub_individual_id"), table_name="pub_eft")
    op.drop_column("pub_eft", "pub_individual_id")
    op.execute(DropSequence(cast(str, Sequence("pub_eft_individual_id_seq"))))
    op.drop_index(op.f("ix_payment_pub_individual_id"), table_name="payment")
    op.drop_column("payment", "pub_individual_id")
    op.execute(DropSequence(cast(str, Sequence("payment_individual_id_seq"))))

    # ### end Alembic commands ###
