"""add not_fraud column to user

Revision ID: da4b82f5bca0
Revises: 60115085565a
Create Date: 2021-07-27 18:43:54.807056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da4b82f5bca0"
down_revision = "60115085565a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("not_fraud", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "not_fraud")
    # ### end Alembic commands ###
