"""Add EmployeeOccupation.organization_unit relationship

Revision ID: d54ca8c8eccb
Revises: 7356c1084235
Create Date: 2021-10-13 15:40:23.878799

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d54ca8c8eccb"
down_revision = "7356c1084235"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee_occupation",
        sa.Column("organization_unit_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_index(
        op.f("ix_employee_occupation_organization_unit_id"),
        "employee_occupation",
        ["organization_unit_id"],
        unique=False,
    )
    op.create_foreign_key(
        "employee_occupation_organization_unit_fkey",
        "employee_occupation",
        "organization_unit",
        ["organization_unit_id"],
        ["organization_unit_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "employee_occupation_organization_unit_fkey", "employee_occupation", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_employee_occupation_organization_unit_id"), table_name="employee_occupation"
    )
    op.drop_column("employee_occupation", "organization_unit_id")
    # ### end Alembic commands ###
