"""Add exclude_from_payment_status to Payment

Revision ID: 40af0e65492a
Revises: 776662d52eb2
Create Date: 2021-11-09 17:53:04.840220

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "40af0e65492a"
down_revision = "776662d52eb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment",
        sa.Column(
            "exclude_from_payment_status", sa.Boolean(), server_default="FALSE", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment", "exclude_from_payment_status")
    # ### end Alembic commands ###
