"""make absence period table fields nullable

Revision ID: 528f8c65980f
Revises: 25cfc76c10c1
Create Date: 2021-09-07 16:33:18.129942

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "528f8c65980f"
down_revision = "69f0b99fed2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "absence_period", "absence_period_type_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "absence_period", "absence_reason_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "absence_period", "leave_request_decision_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "absence_period", "leave_request_decision_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "absence_period", "absence_reason_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "absence_period", "absence_period_type_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
