"""added industry code ref to employer table

Revision ID: b99a1f6a0679
Revises: 45196f9b9bd4
Create Date: 2021-09-24 17:34:27.171290

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, usesd by Alembic.
revision = "b99a1f6a0679"
down_revision = "c3e4440d2a2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employer", sa.Column("industry_code_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "employer", "lk_industry_code", ["industry_code_id"], ["industry_code_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("employer_industry_code_id_fkey", "employer", type_="foreignkey")
    op.drop_column("employer", "industry_code_id")
    # ### end Alembic commands ###
