"""nullable_content_type_table

Revision ID: 458af2d103eb
Revises: 175e38fc50d0
Create Date: 2021-10-21 16:48:11.138836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "458af2d103eb"
down_revision = "175e38fc50d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("document", "content_type_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "dua_employee_demographics",
        "fineos_customer_number",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dua_employee_demographics",
        "fineos_customer_number",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column("document", "content_type_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
