"""PUB-304: Attach employee_id column to payment

Revision ID: 8b8795dc55a7
Revises: 8a9c560dc3b8
Create Date: 2021-09-14 18:45:09.067901

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8b8795dc55a7"
down_revision = "8a9c560dc3b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f("ix_payment_employee_id"), "payment", ["employee_id"], unique=False)
    op.create_foreign_key(None, "payment", "employee", ["employee_id"], ["employee_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.drop_index(op.f("ix_payment_employee_id"), table_name="payment")
    op.drop_column("payment", "employee_id")
    # ### end Alembic commands ###
