"""drop employee.mailing_address_id

Revision ID: b2ef539ff3c3
Revises: a654bf03da3f
Create Date: 2021-05-11 19:58:39.646737

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b2ef539ff3c3"
down_revision = "c911058236e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_employee_mailing_address_id", table_name="employee")
    op.drop_constraint("employee_mailing_address_id_fkey", "employee", type_="foreignkey")
    op.drop_column("employee", "mailing_address_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee",
        sa.Column("mailing_address_id", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "employee_mailing_address_id_fkey",
        "employee",
        "address",
        ["mailing_address_id"],
        ["address_id"],
    )
    op.create_index(
        "ix_employee_mailing_address_id", "employee", ["mailing_address_id"], unique=False
    )
    # ### end Alembic commands ###
