"""Add claim type to payment

Revision ID: ec33b25714f2
Revises: 743f912e4c21
Create Date: 2021-05-10 15:41:43.058028

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec33b25714f2"
down_revision = "743f912e4c21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("claim_type_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "payment_claim_type_id_fkey",
        "payment",
        "lk_claim_type",
        ["claim_type_id"],
        ["claim_type_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.drop_column("payment", "claim_type_id")
    # ### end Alembic commands ###
