"""add unique constraint to tax_identifier_id on employee

Revision ID: 7cdb244e2e15
Revises: 7e4cd8f28ddc
Create Date: 2021-05-27 18:47:23.915430

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "7cdb244e2e15"
down_revision = "7e4cd8f28ddc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_employee_tax_identifier_id", table_name="employee")
    op.create_index(
        op.f("ix_employee_tax_identifier_id"), "employee", ["tax_identifier_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employee_tax_identifier_id"), table_name="employee")
    op.create_index(
        "ix_employee_tax_identifier_id", "employee", ["tax_identifier_id"], unique=False
    )
    # ### end Alembic commands ###
