"""removed has_previous_leaves column from application

Revision ID: 748c18541128
Revises: 7e4cd8f28ddc
Create Date: 2021-05-28 17:27:41.574871

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "748c18541128"
down_revision = "7e4cd8f28ddc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "has_previous_leaves")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application",
        sa.Column("has_previous_leaves", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
