"""Restore primary key on employer_quarterly_contribution

Revision ID: 96649c09c53a
Revises: f9c23f61707e
Create Date: 2021-07-15 12:57:37.520530

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "96649c09c53a"
down_revision = "f9c23f61707e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key(
        "employer_quarterly_contribution_pkey",
        "employer_quarterly_contribution",
        ["employer_id", "filing_period"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "employer_quarterly_contribution_pkey", "employer_quarterly_contribution", type_="primary"
    )
    # ### end Alembic commands ###
