"""Add import log id to state log

Revision ID: c90f256ed616
Revises: 2b67441cb6bb
Create Date: 2021-04-06 16:24:58.087191

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c90f256ed616"
down_revision = "2b67441cb6bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("state_log", sa.Column("import_log_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_state_log_import_log_id"), "state_log", ["import_log_id"], unique=False
    )
    op.create_foreign_key(
        "state_logs_import_log_id_fkey",
        "state_log",
        "import_log",
        ["import_log_id"],
        ["import_log_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("state_logs_import_log_id_fkey", "state_log", type_="foreignkey")
    op.drop_index(op.f("ix_state_log_import_log_id"), table_name="state_log")
    op.drop_column("state_log", "import_log_id")
    # ### end Alembic commands ###
