"""add create_at, updated_at to Claim, User, UserRole, UserLeaveAdministrator

Revision ID: 655510a2930d
Revises: 6960b8da4402
Create Date: 2021-01-18 22:18:14.777545

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "655510a2930d"
down_revision = "6960b8da4402"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "claim",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "claim",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "link_user_leave_administrator",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "link_user_leave_administrator",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "link_user_role",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "link_user_role",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("link_user_role", "updated_at")
    op.drop_column("link_user_role", "created_at")
    op.drop_column("link_user_leave_administrator", "updated_at")
    op.drop_column("link_user_leave_administrator", "created_at")
    op.drop_column("claim", "updated_at")
    op.drop_column("claim", "created_at")
    # ### end Alembic commands ###
