"""add unique constraint to OrgUnit

Revision ID: ae4edb4a80ea
Revises: 40af0e65492a
Create Date: 2021-11-15 16:19:45.598158

"""
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ae4edb4a80ea"
down_revision = "40af0e65492a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization_unit", "employer_id", existing_type=postgresql.UUID(), nullable=False
    )
    op.create_unique_constraint(
        "uix_organization_unit_name_employer_id", "organization_unit", ["name", "employer_id"]
    )
    op.drop_constraint("organization_unit_name_key", "organization_unit", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("organization_unit_name_key", "organization_unit", ["name"])
    op.drop_constraint(
        "uix_organization_unit_name_employer_id", "organization_unit", type_="unique"
    )
    op.alter_column(
        "organization_unit", "employer_id", existing_type=postgresql.UUID(), nullable=True
    )
    # ### end Alembic commands ###
