"""Add pub_eft.prenote_response_reason_code

Revision ID: 87bac6adf3f5
Revises: 48dbfcd9c07e
Create Date: 2021-03-30 17:36:49.635355

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "87bac6adf3f5"
down_revision = "48dbfcd9c07e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pub_eft", sa.Column("prenote_response_reason_code", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pub_eft", "prenote_response_reason_code")
    # ### end Alembic commands ###
