"""Add imported_from_fineos_at timestamp to application table

Revision ID: b83ecbdc3ab2
Revises: 5ddd0ba0df83
Create Date: 2021-12-30 19:51:39.170485

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b83ecbdc3ab2"
down_revision = "5ddd0ba0df83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application",
        sa.Column("imported_from_fineos_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "imported_from_fineos_at")
    # ### end Alembic commands ###
