"""create_wages_and_contributions_history_table

Revision ID: 175e38fc50d0
Revises: 05fd63a41fba
Create Date: 2021-09-30 16:15:04.488690

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "175e38fc50d0"
down_revision = "05fd63a41fba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wages_and_contributions_history",
        sa.Column(
            "wages_and_contributions_history_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_independent_contractor", sa.Boolean(), nullable=False),
        sa.Column("is_opted_in", sa.Boolean(), nullable=False),
        sa.Column("employee_ytd_wages", sa.Numeric(), nullable=False),
        sa.Column("employee_qtr_wages", sa.Numeric(), nullable=False),
        sa.Column("employee_med_contribution", sa.Numeric(), nullable=False),
        sa.Column("employer_med_contribution", sa.Numeric(), nullable=False),
        sa.Column("employee_fam_contribution", sa.Numeric(), nullable=False),
        sa.Column("employer_fam_contribution", sa.Numeric(), nullable=False),
        sa.Column("import_log_id", sa.Integer, nullable=True),
        sa.Column("wage_and_contribution_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["import_log_id"], ["import_log.import_log_id"]),
        sa.ForeignKeyConstraint(
            ["wage_and_contribution_id"], ["wages_and_contributions.wage_and_contribution_id"]
        ),
        sa.PrimaryKeyConstraint("wages_and_contributions_history_id"),
    )
    op.create_index(
        op.f("ix_wages_and_contributions_history_wage_and_contribution_id"),
        "wages_and_contributions_history",
        ["wage_and_contribution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wages_and_contributions_history_import_log_id"),
        "wages_and_contributions_history",
        ["import_log_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wages_and_contributions_history_wage_and_contribution_id"),
        table_name="wages_and_contributions_history",
    )
    op.drop_index(
        op.f("ix_wages_and_contributions_history_import_log_id"),
        table_name="wages_and_contributions_history",
    )
    op.drop_table("wages_and_contributions_history")
    # ### end Alembic commands ###
