"""Created Link Table for DuaReductionPayment and ReferenceFile

Revision ID: 850ae5efc4ee
Revises: 8260211a3877
Create Date: 2021-02-24 16:20:31.363312

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "850ae5efc4ee"
down_revision = "8260211a3877"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link_dua_reduction_payment_reference_file",
        sa.Column("dua_reduction_payment_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("reference_file_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dua_reduction_payment_id"], ["dua_reduction_payment.dua_reduction_payment_id"]
        ),
        sa.ForeignKeyConstraint(["reference_file_id"], ["reference_file.reference_file_id"]),
        sa.PrimaryKeyConstraint("dua_reduction_payment_id", "reference_file_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("link_dua_reduction_payment_reference_file")
    # ### end Alembic commands ###
