"""add-created-at-to-reference-files

Revision ID: 2fbc25c28b0e
Revises: 14155f78d8e6
Create Date: 2021-01-29 19:57:00.791535

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2fbc25c28b0e"
down_revision = "14155f78d8e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reference_file",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reference_file", "created_at")
    # ### end Alembic commands ###
