"""Added fineos gender description

Revision ID: fd61facec777
Revises: 86db3c551ac6
Create Date: 2021-04-21 16:13:01.386761

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fd61facec777"
down_revision = "86db3c551ac6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lk_gender", sa.Column("fineos_gender_description", sa.Text(), nullable=True))
    op.execute(
        "UPDATE lk_gender SET fineos_gender_description = 'Male' WHERE gender_description = 'Man'"
    )
    op.execute(
        "UPDATE lk_gender SET fineos_gender_description = 'Female' WHERE gender_description = 'Woman'"
    )
    op.execute(
        "UPDATE lk_gender SET fineos_gender_description = 'Neutral' WHERE gender_description = 'Nonbinary'"
    )
    op.execute(
        "UPDATE lk_gender SET fineos_gender_description = 'Unknown' WHERE gender_description = 'Gender not listed'"
    )
    op.alter_column("lk_gender", "fineos_gender_description", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lk_gender", "fineos_gender_description")
    # ### end Alembic commands ###
