"""add fineos_absence_id and notification_id to claim table

Revision ID: eae0700422cb
Revises: 850ae5efc4ee
Create Date: 2021-03-08 16:36:24.365218

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "eae0700422cb"
down_revision = "850ae5efc4ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO
            claim(
            claim_id,
            fineos_absence_id,
            fineos_notification_id,
            employer_id,
            created_at,
            updated_at
            )
        SELECT
            public.gen_random_uuid(),
            fineos_absence_id,
            fineos_notification_case_id,
            employer_id,
            now(),
            now()
        FROM
            application
        WHERE
            fineos_absence_id IS NOT NULL
            AND fineos_notification_case_id IS NOT NULL
            AND claim_id IS NULL
        ON CONFLICT
            DO NOTHING
        """
    )
    op.execute(
        "UPDATE application SET claim_id = claim.claim_id FROM claim WHERE application.fineos_absence_id = claim.fineos_absence_id"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE application SET fineos_absence_id=claim.fineos_absence_id, fineos_notification_case_id=claim.fineos_notification_id FROM claim WHERE application.claim_id = claim.claim_id"
    )

    # ### end Alembic commands ###
