"""PUB Error with types

Revision ID: e679239bb86b
Revises: 3e9650966949
Create Date: 2021-04-02 16:06:16.159565

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e679239bb86b"
down_revision = "e4ec4cc9647d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_pub_error_type",
        sa.Column("pub_error_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pub_error_type_description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("pub_error_type_id"),
    )
    op.create_table(
        "pub_error",
        sa.Column("pub_error_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("pub_error_type_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("type_code", sa.Integer(), nullable=False),
        sa.Column("raw_data", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("payment_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("pub_eft_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("import_log_id", sa.Integer(), nullable=False),
        sa.Column("reference_file_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["import_log_id"], ["import_log.import_log_id"]),
        sa.ForeignKeyConstraint(["payment_id"], ["payment.payment_id"]),
        sa.ForeignKeyConstraint(["pub_eft_id"], ["pub_eft.pub_eft_id"]),
        sa.ForeignKeyConstraint(["pub_error_type_id"], ["lk_pub_error_type.pub_error_type_id"]),
        sa.ForeignKeyConstraint(["reference_file_id"], ["reference_file.reference_file_id"]),
        sa.PrimaryKeyConstraint("pub_error_id", "reference_file_id"),
    )
    op.create_index(
        op.f("ix_pub_error_import_log_id"), "pub_error", ["import_log_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pub_error_import_log_id"), table_name="pub_error")
    op.drop_table("pub_error")
    op.drop_table("lk_pub_error_type")
    # ### end Alembic commands ###
