"""add tables to hold IAWW extract data

Revision ID: 59394f6a082a
Revises: 2ef7a3835814
Create Date: 2021-11-24 00:10:21.325919

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "59394f6a082a"
down_revision = "2ef7a3835814"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fineos_extract_v_paid_leave_instruction",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("paid_leave_instruction_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("c", sa.Text(), nullable=True),
        sa.Column("i", sa.Text(), nullable=True),
        sa.Column("flags", sa.Text(), nullable=True),
        sa.Column("partitionid", sa.Text(), nullable=True),
        sa.Column("lastupdatedate", sa.Text(), nullable=True),
        sa.Column("boeversion", sa.Text(), nullable=True),
        sa.Column("c_osuser_updatedby", sa.Text(), nullable=True),
        sa.Column("i_osuser_updatedby", sa.Text(), nullable=True),
        sa.Column("averagedaysworked", sa.Text(), nullable=True),
        sa.Column("averageweeklywage_monamt", sa.Text(), nullable=True),
        sa.Column("averageweeklywage_moncur", sa.Text(), nullable=True),
        sa.Column("benefitwaitingperiod", sa.Text(), nullable=True),
        sa.Column("doesmandatoryfitapply", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("policyreference", sa.Text(), nullable=True),
        sa.Column("taxablepercentage", sa.Text(), nullable=True),
        sa.Column("autoapprovebenefits", sa.Text(), nullable=True),
        sa.Column("benefitwaitingperiodbasis", sa.Text(), nullable=True),
        sa.Column("c_selectedleaveplan", sa.Text(), nullable=True),
        sa.Column("i_selectedleaveplan", sa.Text(), nullable=True),
        sa.Column("reference_file_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("fineos_extract_import_log_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["fineos_extract_import_log_id"], ["import_log.import_log_id"]),
        sa.ForeignKeyConstraint(["reference_file_id"], ["reference_file.reference_file_id"]),
        sa.PrimaryKeyConstraint("paid_leave_instruction_id"),
    )
    op.create_index(
        op.f("ix_fineos_extract_v_paid_leave_instruction_fineos_extract_import_log_id"),
        "fineos_extract_v_paid_leave_instruction",
        ["fineos_extract_import_log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fineos_extract_v_paid_leave_instruction_reference_file_id"),
        "fineos_extract_v_paid_leave_instruction",
        ["reference_file_id"],
        unique=False,
    )
    op.create_table(
        "fineos_extract_vbi_leave_plan_requested_absence",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("leave_plan_requested_absence_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("selectedplan_classid", sa.Text(), nullable=True),
        sa.Column("selectedplan_indexid", sa.Text(), nullable=True),
        sa.Column("selectedplan_lastupdatedate", sa.Text(), nullable=True),
        sa.Column("selectedplan_adjudicat_result", sa.Text(), nullable=True),
        sa.Column("selectedplan_adjudication_note", sa.Text(), nullable=True),
        sa.Column("selectedplan_updatedbyuserid", sa.Text(), nullable=True),
        sa.Column("leaveplan_classid", sa.Text(), nullable=True),
        sa.Column("leaveplan_indexid", sa.Text(), nullable=True),
        sa.Column("leaveplan_displayreference", sa.Text(), nullable=True),
        sa.Column("leaveplan_shortname", sa.Text(), nullable=True),
        sa.Column("leaveplan_longname", sa.Text(), nullable=True),
        sa.Column("leaveplan_alias", sa.Text(), nullable=True),
        sa.Column("leaveplan_leavegroup", sa.Text(), nullable=True),
        sa.Column("leaveplan_leavecategory", sa.Text(), nullable=True),
        sa.Column("leaveplan_leavetype", sa.Text(), nullable=True),
        sa.Column("leaveplan_state", sa.Text(), nullable=True),
        sa.Column("leaveplan_jobprotection", sa.Text(), nullable=True),
        sa.Column("leaverequest_id", sa.Text(), nullable=True),
        sa.Column("reference_file_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("fineos_extract_import_log_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["fineos_extract_import_log_id"], ["import_log.import_log_id"]),
        sa.ForeignKeyConstraint(["reference_file_id"], ["reference_file.reference_file_id"]),
        sa.PrimaryKeyConstraint("leave_plan_requested_absence_id"),
    )
    op.create_index(
        op.f("ix_fineos_extract_vbi_leave_plan_requested_absence_fineos_extract_import_log_id"),
        "fineos_extract_vbi_leave_plan_requested_absence",
        ["fineos_extract_import_log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fineos_extract_vbi_leave_plan_requested_absence_reference_file_id"),
        "fineos_extract_vbi_leave_plan_requested_absence",
        ["reference_file_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fineos_extract_vbi_leave_plan_requested_absence_reference_file_id"),
        table_name="fineos_extract_vbi_leave_plan_requested_absence",
    )
    op.drop_index(
        op.f("ix_fineos_extract_vbi_leave_plan_requested_absence_fineos_extract_import_log_id"),
        table_name="fineos_extract_vbi_leave_plan_requested_absence",
    )
    op.drop_table("fineos_extract_vbi_leave_plan_requested_absence")
    op.drop_index(
        op.f("ix_fineos_extract_v_paid_leave_instruction_reference_file_id"),
        table_name="fineos_extract_v_paid_leave_instruction",
    )
    op.drop_index(
        op.f("ix_fineos_extract_v_paid_leave_instruction_fineos_extract_import_log_id"),
        table_name="fineos_extract_v_paid_leave_instruction",
    )
    op.drop_table("fineos_extract_v_paid_leave_instruction")
    # ### end Alembic commands ###
