"""add average weekly wage column to absence period table

Revision ID: 7a466c88cc9a
Revises: 02cad5487ef0
Create Date: 2021-11-18 06:14:22.289387

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a466c88cc9a"
down_revision = "02cad5487ef0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "absence_period", sa.Column("fineos_average_weekly_wage", sa.Numeric(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("absence_period", "fineos_average_weekly_wage")
    # ### end Alembic commands ###
