"""drop other_incomes_awaiting_approval column

Revision ID: 78833d1dd679
Revises: 58f3a90c4796
Create Date: 2021-07-06 15:07:53.446184

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "78833d1dd679"
down_revision = "58f3a90c4796"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "other_incomes_awaiting_approval")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application",
        sa.Column(
            "other_incomes_awaiting_approval", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
