"""Make EFT numerics strings

Revision ID: f45815e3cf63
Revises: 15b2eaf586d7
Create Date: 2021-01-08 16:28:51.982308

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f45815e3cf63"
down_revision = "f20a1058b17b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "eft", "account_nbr", existing_type=sa.INTEGER(), type_=sa.Text(), existing_nullable=False
    )
    op.alter_column(
        "eft", "routing_nbr", existing_type=sa.INTEGER(), type_=sa.Text(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE eft ALTER COLUMN routing_nbr TYPE integer USING (routing_nbr::integer)")
    op.execute("ALTER TABLE eft ALTER COLUMN account_nbr TYPE integer USING (account_nbr::integer)")

    # ### end Alembic commands ###
