"""Add payment check number column

Revision ID: 3e9650966949
Revises: 87bac6adf3f5
Create Date: 2021-03-31 16:36:54.238417

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3e9650966949"
down_revision = "87bac6adf3f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("check_number", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "payment", ["check_number"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment", type_="unique")
    op.drop_column("payment", "check_number")
    # ### end Alembic commands ###
