"""fineos employee name

Revision ID: 25cfc76c10c1
Revises: cceaf8646052
Create Date: 2021-08-30 14:30:40.045074

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "25cfc76c10c1"
down_revision = "cceaf8646052"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employee", sa.Column("fineos_employee_first_name", sa.Text(), nullable=True))
    op.add_column("employee", sa.Column("fineos_employee_last_name", sa.Text(), nullable=True))
    op.add_column("employee", sa.Column("fineos_employee_middle_name", sa.Text(), nullable=True))
    op.add_column("payment", sa.Column("fineos_employee_first_name", sa.Text(), nullable=True))
    op.add_column("payment", sa.Column("fineos_employee_last_name", sa.Text(), nullable=True))
    op.add_column("payment", sa.Column("fineos_employee_middle_name", sa.Text(), nullable=True))
    op.add_column("pub_eft", sa.Column("fineos_employee_first_name", sa.Text(), nullable=True))
    op.add_column("pub_eft", sa.Column("fineos_employee_last_name", sa.Text(), nullable=True))
    op.add_column("pub_eft", sa.Column("fineos_employee_middle_name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pub_eft", "fineos_employee_middle_name")
    op.drop_column("pub_eft", "fineos_employee_last_name")
    op.drop_column("pub_eft", "fineos_employee_first_name")
    op.drop_column("payment", "fineos_employee_middle_name")
    op.drop_column("payment", "fineos_employee_last_name")
    op.drop_column("payment", "fineos_employee_first_name")
    op.drop_column("employee", "fineos_employee_middle_name")
    op.drop_column("employee", "fineos_employee_last_name")
    op.drop_column("employee", "fineos_employee_first_name")
    # ### end Alembic commands ###
