"""removed fineos_absence_id and fineos_notification_id from application table

Revision ID: 61fa9de81415
Revises: 8260211a3877
Create Date: 2021-02-23 19:54:55.620063

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "61fa9de81415"
down_revision = "8260211a3877"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_application_fineos_absence_id", table_name="application")
    op.drop_index("ix_application_fineos_notification_case_id", table_name="application")
    op.drop_column("application", "fineos_absence_id")
    op.drop_column("application", "fineos_notification_case_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application",
        sa.Column("fineos_notification_case_id", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "application", sa.Column("fineos_absence_id", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index(
        "ix_application_fineos_notification_case_id",
        "application",
        ["fineos_notification_case_id"],
        unique=False,
    )
    op.create_index(
        "ix_application_fineos_absence_id", "application", ["fineos_absence_id"], unique=False
    )
    op.execute(
        "UPDATE application SET fineos_absence_id=claim.fineos_absence_id, fineos_notification_case_id=claim.fineos_notification_id FROM claim WHERE application.claim_id = claim.claim_id"
    )
    # ### end Alembic commands ###
