"""API-1970: Add reference file processed import log ID and indexes

Revision ID: 2236f00cf4e7
Revises: 6bcd77eaa8c9
Create Date: 2021-10-15 14:04:10.083386

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2236f00cf4e7"
down_revision = "6bcd77eaa8c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_fineos_extract_employee_feed_customerno"),
        "fineos_extract_employee_feed",
        ["customerno"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fineos_extract_vbi_requested_absence_leaverequest_id"),
        "fineos_extract_vbi_requested_absence",
        ["leaverequest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fineos_extract_vpei_claim_details_peclassid"),
        "fineos_extract_vpei_claim_details",
        ["peclassid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fineos_extract_vpei_claim_details_peindexid"),
        "fineos_extract_vpei_claim_details",
        ["peindexid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fineos_extract_vpei_payment_details_peclassid"),
        "fineos_extract_vpei_payment_details",
        ["peclassid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fineos_extract_vpei_payment_details_peindexid"),
        "fineos_extract_vpei_payment_details",
        ["peindexid"],
        unique=False,
    )
    op.add_column("payment", sa.Column("vpei_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(
        "payment_fineos_extract_vpei_fkey",
        "payment",
        "fineos_extract_vpei",
        ["vpei_id"],
        ["vpei_id"],
    )
    op.add_column(
        "reference_file", sa.Column("processed_import_log_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_reference_file_processed_import_log_id"),
        "reference_file",
        ["processed_import_log_id"],
        unique=False,
    )
    op.create_foreign_key(
        "reference_file_import_log_fkey",
        "reference_file",
        "import_log",
        ["processed_import_log_id"],
        ["import_log_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("reference_file_import_log_fkey", "reference_file", type_="foreignkey")
    op.drop_index(op.f("ix_reference_file_processed_import_log_id"), table_name="reference_file")
    op.drop_column("reference_file", "processed_import_log_id")
    op.drop_constraint("payment_fineos_extract_vpei_fkey", "payment", type_="foreignkey")
    op.drop_column("payment", "vpei_id")
    op.drop_index(
        op.f("ix_fineos_extract_vpei_payment_details_peindexid"),
        table_name="fineos_extract_vpei_payment_details",
    )
    op.drop_index(
        op.f("ix_fineos_extract_vpei_payment_details_peclassid"),
        table_name="fineos_extract_vpei_payment_details",
    )
    op.drop_index(
        op.f("ix_fineos_extract_vpei_claim_details_peindexid"),
        table_name="fineos_extract_vpei_claim_details",
    )
    op.drop_index(
        op.f("ix_fineos_extract_vpei_claim_details_peclassid"),
        table_name="fineos_extract_vpei_claim_details",
    )
    op.drop_index(
        op.f("ix_fineos_extract_vbi_requested_absence_leaverequest_id"),
        table_name="fineos_extract_vbi_requested_absence",
    )
    op.drop_index(
        op.f("ix_fineos_extract_employee_feed_customerno"),
        table_name="fineos_extract_employee_feed",
    )
    # ### end Alembic commands ###
