"""adds claim_id to application table

Revision ID: a876933b8a24
Revises: 937eeca0b089
Create Date: 2021-01-26 19:39:16.474395

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a876933b8a24"
down_revision = "937eeca0b089"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application", sa.Column("claim_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.create_unique_constraint(None, "application", ["claim_id"])
    op.create_foreign_key(None, "application", "claim", ["claim_id"], ["claim_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "application", type_="foreignkey")
    op.drop_constraint(None, "application", type_="unique")
    op.drop_column("application", "claim_id")
    # ### end Alembic commands ###
