"""Make all lookup table descriptions non-nullable

Revision ID: 8a9c560dc3b8
Revises: 2d843c0a0613
Create Date: 2021-09-02 18:01:56.807613

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8a9c560dc3b8"
down_revision = "2d843c0a0613"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lk_absence_period_type",
        "absence_period_type_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_absence_reason", "absence_reason_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "lk_absence_reason_qualifier_one",
        "absence_reason_qualifier_one_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_absence_reason_qualifier_two",
        "absence_reason_qualifier_two_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_absence_status", "absence_status_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "lk_address_type", "address_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "lk_amount_frequency",
        "amount_frequency_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_bank_account_type",
        "bank_account_type_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_claim_type", "claim_type_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column("lk_country", "country_description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "lk_day_of_week", "day_of_week_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "lk_education_level", "education_level_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "lk_employer_benefit_type",
        "employer_benefit_type_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_employment_status",
        "employment_status_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_fineos_writeback_transaction_status",
        "transaction_status_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column("lk_flow", "flow_description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "lk_frequency_or_duration",
        "frequency_or_duration_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column("lk_gender", "gender_description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "lk_geo_state", "geo_state_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "lk_leave_reason", "leave_reason_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "lk_leave_reason_qualifier",
        "leave_reason_qualifier_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_leave_request_decision",
        "leave_request_decision_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_managed_requirement_category",
        "managed_requirement_category_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_managed_requirement_status",
        "managed_requirement_status_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_managed_requirement_type",
        "managed_requirement_type_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_marital_status", "marital_status_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "lk_notification_method",
        "notification_method_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_occupation", "occupation_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "lk_other_income_type",
        "other_income_type_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_payment_check_status",
        "payment_check_status_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_payment_method", "payment_method_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "lk_payment_transaction_type",
        "payment_transaction_type_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_prenote_state", "prenote_state_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "lk_previous_leave_qualifying_reason",
        "previous_leave_qualifying_reason_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_pub_error_type", "pub_error_type_description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column("lk_race", "race_description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "lk_reference_file_type",
        "reference_file_type_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_relationship_qualifier",
        "relationship_qualifier_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_relationship_to_caregiver",
        "relationship_to_caregiver_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column("lk_role", "role_description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("lk_state", "state_description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("lk_title", "title_description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "lk_verification_type",
        "verification_type_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "lk_work_pattern_type",
        "work_pattern_type_description",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lk_work_pattern_type",
        "work_pattern_type_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_verification_type",
        "verification_type_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column("lk_title", "title_description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("lk_state", "state_description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("lk_role", "role_description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "lk_relationship_to_caregiver",
        "relationship_to_caregiver_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_relationship_qualifier",
        "relationship_qualifier_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_reference_file_type",
        "reference_file_type_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column("lk_race", "race_description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "lk_pub_error_type", "pub_error_type_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "lk_previous_leave_qualifying_reason",
        "previous_leave_qualifying_reason_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_prenote_state", "prenote_state_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "lk_payment_transaction_type",
        "payment_transaction_type_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_payment_method", "payment_method_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "lk_payment_check_status",
        "payment_check_status_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_other_income_type",
        "other_income_type_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_occupation", "occupation_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "lk_notification_method",
        "notification_method_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_marital_status", "marital_status_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "lk_managed_requirement_type",
        "managed_requirement_type_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_managed_requirement_status",
        "managed_requirement_status_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_managed_requirement_category",
        "managed_requirement_category_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_leave_request_decision",
        "leave_request_decision_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_leave_reason_qualifier",
        "leave_reason_qualifier_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_leave_reason", "leave_reason_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column("lk_geo_state", "geo_state_description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("lk_gender", "gender_description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "lk_frequency_or_duration",
        "frequency_or_duration_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column("lk_flow", "flow_description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "lk_fineos_writeback_transaction_status",
        "transaction_status_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_employment_status",
        "employment_status_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_employer_benefit_type",
        "employer_benefit_type_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_education_level", "education_level_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "lk_day_of_week", "day_of_week_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column("lk_country", "country_description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "lk_claim_type", "claim_type_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "lk_bank_account_type",
        "bank_account_type_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_amount_frequency",
        "amount_frequency_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_address_type", "address_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "lk_absence_status", "absence_status_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "lk_absence_reason_qualifier_two",
        "absence_reason_qualifier_two_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_absence_reason_qualifier_one",
        "absence_reason_qualifier_one_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "lk_absence_reason", "absence_reason_description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "lk_absence_period_type",
        "absence_period_type_description",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###
