"""add occupation_code column to lk_occupation

Revision ID: 7c2abdcf72de
Revises: f179009904e7
Create Date: 2021-04-28 18:37:43.676535

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7c2abdcf72de"
down_revision = "f179009904e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lk_occupation", sa.Column("occupation_code", sa.Integer(), nullable=True))
    op.create_unique_constraint("lk_occupation_code_key", "lk_occupation", ["occupation_code"])

    op.create_table(
        "lk_occupation_title",
        sa.Column("occupation_title_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("occupation_id", sa.Integer(), nullable=True),
        sa.Column("occupation_title_code", sa.Integer(), nullable=True),
        sa.Column("occupation_title_description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["occupation_id"], ["lk_occupation.occupation_id"],),
        sa.PrimaryKeyConstraint("occupation_title_id"),
    )

    op.create_table(
        "application_occupation",
        sa.Column("application_occupation_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("occupation_title_id", sa.Integer(), nullable=True),
        sa.Column("job_title", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["occupation_title_id"], ["lk_occupation_title.occupation_title_id"],),
        sa.PrimaryKeyConstraint("application_occupation_id"),
    )

    op.drop_constraint("application_occupation_id_fkey", "application", type_="foreignkey")
    op.drop_column("application", "occupation_id")
    op.add_column("application", sa.Column("occupation_id", postgresql.UUID(), nullable=True))
    op.create_foreign_key("application_occupation_id_fkey", "application", "application_occupation", ["occupation_id"], ["application_occupation_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lk_occupation", "occupation_code")

    op.drop_constraint("application_occupation_id_fkey", "application", type_="foreignkey")
    op.drop_column("application", "occupation_id")
    op.add_column("application", sa.Column("occupation_id", sa.Integer(), nullable=True))
    op.create_foreign_key("application_occupation_id_fkey", "application", "lk_occupation", ["occupation_id"], ["occupation_id"])

    op.drop_table("application_occupation")
    op.drop_table("lk_occupation_title")
