"""PUB-130: Payments have experian address

Revision ID: b3c55c26e2d3
Revises: 2b67441cb6bb
Create Date: 2021-04-06 17:25:25.643971

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b3c55c26e2d3"
down_revision = "7fbb85a42f6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_employee_experian_address_pair_id", table_name="employee")
    op.drop_constraint("employee_experian_address_pair_id_fkey", "employee", type_="foreignkey")
    op.drop_column("employee", "experian_address_pair_id")
    op.add_column(
        "payment",
        sa.Column("experian_address_pair_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_index(
        op.f("ix_payment_experian_address_pair_id"),
        "payment",
        ["experian_address_pair_id"],
        unique=False,
    )
    op.create_foreign_key(
        "payment_link_experian_address_pair_fkey",
        "payment",
        "link_experian_address_pair",
        ["experian_address_pair_id"],
        ["fineos_address_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("payment_link_experian_address_pair_fkey", "payment", type_="foreignkey")
    op.drop_index(op.f("ix_payment_experian_address_pair_id"), table_name="payment")
    op.drop_column("payment", "experian_address_pair_id")
    op.add_column(
        "employee",
        sa.Column(
            "experian_address_pair_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "employee_experian_address_pair_id_fkey",
        "employee",
        "link_experian_address_pair",
        ["experian_address_pair_id"],
        ["fineos_address_id"],
    )
    op.create_index(
        "ix_employee_experian_address_pair_id",
        "employee",
        ["experian_address_pair_id"],
        unique=False,
    )
    # ### end Alembic commands ###
