"""pub experian check constraints

Revision ID: 2b67441cb6bb
Revises: e679239bb86b
Create Date: 2021-04-02 17:12:14.725771

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "2b67441cb6bb"
down_revision = "e679239bb86b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "link_experian_address_pair_fineos_address_id",
        "link_experian_address_pair",
        ["fineos_address_id"],
    )
    op.create_index(op.f("ix_payment_check_number"), "payment", ["check_number"], unique=True)
    op.drop_constraint("payment_check_number_key", "payment", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("payment_check_number_key", "payment", ["check_number"])
    op.drop_index(op.f("ix_payment_check_number"), table_name="payment")
    op.drop_constraint(
        "link_experian_address_pair_fineos_address_id", "link_experian_address_pair", type_="unique"
    )
    # ### end Alembic commands ###
