"""drop User.active_directory_id that was renamed to .sub_id

Revision ID: 2d843c0a0613
Revises: c6d26b935c2c
Create Date: 2021-08-31 15:44:54.519695

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2d843c0a0613"
down_revision = "25cfc76c10c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_active_directory_id", table_name="user")
    op.drop_column("user", "active_directory_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("active_directory_id", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_user_active_directory_id", "user", ["active_directory_id"], unique=True)
    # ### end Alembic commands ###
