"""make fineos_customer_number nullable

Revision ID: 3765c13fe7e6
Revises: 175e38fc50d0
Create Date: 2021-10-21 18:43:36.858421

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3765c13fe7e6"
down_revision = "175e38fc50d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dua_employee_demographics",
        "fineos_customer_number",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dua_employee_demographics",
        "fineos_customer_number",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    # ### end Alembic commands ###
