"""Create ExperianAddressPair

Revision ID: b7b658d3168b
Revises: f767b22ae747
Create Date: 2021-03-26 13:54:11.428478

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b7b658d3168b"
down_revision = "f767b22ae747"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link_experian_address_pair",
        sa.Column("fineos_address_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("experian_address_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["experian_address_id"], ["address.address_id"]),
        sa.ForeignKeyConstraint(["fineos_address_id"], ["address.address_id"]),
        sa.PrimaryKeyConstraint("fineos_address_id"),
        sa.UniqueConstraint("fineos_address_id"),
    )
    op.create_index(
        op.f("ix_link_experian_address_pair_experian_address_id"),
        "link_experian_address_pair",
        ["experian_address_id"],
        unique=False,
    )
    op.add_column(
        "employee",
        sa.Column("experian_address_pair_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_index(
        op.f("ix_employee_experian_address_pair_id"),
        "employee",
        ["experian_address_pair_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "employee",
        "link_experian_address_pair",
        ["experian_address_pair_id"],
        ["fineos_address_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employee", type_="foreignkey")  # type: ignore
    op.drop_index(op.f("ix_employee_experian_address_pair_id"), table_name="employee")
    op.drop_column("employee", "experian_address_pair_id")
    op.drop_index(
        op.f("ix_link_experian_address_pair_experian_address_id"),
        table_name="link_experian_address_pair",
    )
    op.drop_table("link_experian_address_pair")
    # ### end Alembic commands ###
