"""new columns for fineos status and s3 location

Revision ID: 1caaec619dd3
Revises: 3561b8166511
Create Date: 2021-12-16 15:21:02.457786

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1caaec619dd3"
down_revision = "3561b8166511"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pfml_1099", sa.Column("s3_location", sa.Text(), nullable=True))
    op.add_column("pfml_1099", sa.Column("fineos_status", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pfml_1099", "fineos_status")
    op.drop_column("pfml_1099", "s3_location")
    # ### end Alembic commands ###
