"""remove_content_type_table

Revision ID: 3e14d30da6ff
Revises: e0506a86aaca
Create Date: 2021-10-19 14:41:44.782005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e14d30da6ff"
down_revision = "e0506a86aaca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("document_content_type_id_fkey", "document", type_="foreignkey")
    op.drop_column("document", "content_type_id")
    op.drop_table("lk_content_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_content_type",
        sa.Column("content_type_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("content_type_description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("content_type_id", name="lk_content_type_pkey"),
    )
    op.add_column(
        "document", sa.Column("content_type_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        "document_content_type_id_fkey",
        "document",
        "lk_content_type",
        ["content_type_id"],
        ["content_type_id"],
    )

    # ### end Alembic commands ###
