"""Adding Withholding Type

Revision ID: 15b3effe5592
Revises: bd0b3cffc68e
Create Date: 2021-10-29 16:50:46.298832

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "15b3effe5592"
down_revision = "bd0b3cffc68e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_withholding_type",
        sa.Column("withholding_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("withholding_type_description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("withholding_type_id"),
    )
    op.add_column(
        "pfml_1099_withholding", sa.Column("withholding_type_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "pfml_1099_withholding",
        "lk_withholding_type",
        ["withholding_type_id"],
        ["withholding_type_id"],
    )
    op.create_index(
        op.f("ix_pfml_1099_withholding_withholding_type_id"),
        "pfml_1099_withholding",
        ["withholding_type_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pfml_1099_withholding_withholding_type_id"), table_name="pfml_1099_withholding"
    )
    op.drop_constraint(
        "pfml_1099_withholding_withholding_type_id_fkey",
        "pfml_1099_withholding",
        type_="foreignkey",
    )
    op.drop_column("pfml_1099_withholding", "withholding_type_id")
    op.drop_table("lk_withholding_type")
    # ### end Alembic commands ###
