"""create occupation_title table

Revision ID: b62f2efc017c
Revises: 7c2abdcf72de
Create Date: 2021-04-28 20:32:11.117092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b62f2efc017c"
down_revision = "7c2abdcf72de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "lk_occupation", ["occupation_code"])
    op.create_table(
        "lk_occupation_title",
        sa.Column("occupation_title_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("occupation_title_description", sa.Text(), nullable=True),
        sa.Column("occupation_code", sa.Integer(), nullable=True),
        sa.Column("occupation_title_code", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["occupation_code"], ["lk_occupation.occupation_code"],),
        sa.PrimaryKeyConstraint("occupation_title_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lk_occupation", type_="unique")
    op.drop_table("lk_occupation_title")
    # ### end Alembic commands ###
