"""rename 1099 tables

Revision ID: bb4a8464905e
Revises: 95d3e464a5b2
Create Date: 2021-10-05 16:09:45.947515

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "bb4a8464905e"
down_revision = "95d3e464a5b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ix_employee_occupation_employee_id_employer_id", "employee_occupation", type_="unique"
    )
    op.create_index(
        "ix_employee_occupation_employee_id_employer_id",
        "employee_occupation",
        ["employee_id", "employer_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_pfml_1099_pfml_1099_batch_id"), "pfml_1099", ["pfml_1099_batch_id"], unique=False
    )
    op.drop_index("ix_pfml_1099_pfml_1009_batch_id", table_name="pfml_1099")
    op.create_index(
        op.f("ix_pfml_1099_mmars_payment_pfml_1099_batch_id"),
        "pfml_1099_mmars_payment",
        ["pfml_1099_batch_id"],
        unique=False,
    )
    op.drop_index(
        "ix_pfml_1099_mmars_payment_pfml_1009_batch_id", table_name="pfml_1099_mmars_payment"
    )
    op.create_index(
        op.f("ix_pfml_1099_payment_pfml_1099_batch_id"),
        "pfml_1099_payment",
        ["pfml_1099_batch_id"],
        unique=False,
    )
    op.drop_index("ix_pfml_1099_payment_pfml_1009_batch_id", table_name="pfml_1099_payment")
    op.create_index(
        op.f("ix_pfml_1099_refund_pfml_1099_batch_id"),
        "pfml_1099_refund",
        ["pfml_1099_batch_id"],
        unique=False,
    )
    op.drop_index("ix_pfml_1099_refund_pfml_1009_batch_id", table_name="pfml_1099_refund")
    op.create_index(
        op.f("ix_pfml_1099_withholding_pfml_1099_batch_id"),
        "pfml_1099_withholding",
        ["pfml_1099_batch_id"],
        unique=False,
    )
    op.drop_index("ix_pfml_1099_withholding_pfml_1009_batch_id", table_name="pfml_1099_withholding")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_pfml_1099_withholding_pfml_1009_batch_id",
        "pfml_1099_withholding",
        ["pfml_1099_batch_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_pfml_1099_withholding_pfml_1099_batch_id"), table_name="pfml_1099_withholding"
    )
    op.create_index(
        "ix_pfml_1099_refund_pfml_1009_batch_id",
        "pfml_1099_refund",
        ["pfml_1099_batch_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_pfml_1099_refund_pfml_1099_batch_id"), table_name="pfml_1099_refund")
    op.create_index(
        "ix_pfml_1099_payment_pfml_1009_batch_id",
        "pfml_1099_payment",
        ["pfml_1099_batch_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_pfml_1099_payment_pfml_1099_batch_id"), table_name="pfml_1099_payment")
    op.create_index(
        "ix_pfml_1099_mmars_payment_pfml_1009_batch_id",
        "pfml_1099_mmars_payment",
        ["pfml_1099_batch_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_pfml_1099_mmars_payment_pfml_1099_batch_id"), table_name="pfml_1099_mmars_payment"
    )
    op.create_index(
        "ix_pfml_1099_pfml_1009_batch_id", "pfml_1099", ["pfml_1099_batch_id"], unique=False
    )
    op.drop_index(op.f("ix_pfml_1099_pfml_1099_batch_id"), table_name="pfml_1099")
    op.drop_index(
        "ix_employee_occupation_employee_id_employer_id", table_name="employee_occupation"
    )
    op.create_unique_constraint(
        "ix_employee_occupation_employee_id_employer_id",
        "employee_occupation",
        ["employee_id", "employer_id"],
    )
    # ### end Alembic commands ###
