"""remove org_unit_name from employee occupation

Revision ID: 1aa29a4fcebc
Revises: 175e38fc50d0
Create Date: 2021-10-21 15:02:18.466467

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1aa29a4fcebc"
down_revision = "ae4edb4a80ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### Create organization_unit rows for all unique employee_occupation.org_unit_name
    # values and drop employee_occupation.org_unit_name

    # ## Insert new Organizations into OrganizationUnit table
    op.execute(
        """
            INSERT INTO organization_unit (organization_unit_id, name, employer_id)
              SELECT public.gen_random_uuid(), org_unit_name, employer_id
              FROM employee_occupation
              WHERE org_unit_name IS NOT NULL
                AND org_unit_name != ''
            ON CONFLICT DO NOTHING
        """
    )

    # ## Update EmployeeOccupation table with organization_unit_id
    op.execute(
        """
            UPDATE employee_occupation
            SET
             organization_unit_id = ou.organization_unit_id
            FROM organization_unit ou
            WHERE ou.name = org_unit_name
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee_occupation", "org_unit_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee_occupation",
        sa.Column("org_unit_name", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
