"""Adding new batch status column

Revision ID: efbf721141cb
Revises: 3765c13fe7e6
Create Date: 2021-10-22 13:35:24.339850

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "efbf721141cb"
down_revision = "3765c13fe7e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pfml_1099_batch", sa.Column("batch_status", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pfml_1099_batch", "batch_status")
    # ### end Alembic commands ###
