"""Add to payments fineos leave request id

Revision ID: 7b183dd23b33
Revises: b0af0d4f18b3
Create Date: 2022-01-26 20:58:03.564738

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b183dd23b33"
down_revision = "b0af0d4f18b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("fineos_leave_request_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_payment_fineos_leave_request_id"),
        "payment",
        ["fineos_leave_request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_fineos_leave_request_id"), table_name="payment")
    op.drop_column("payment", "fineos_leave_request_id")
    # ### end Alembic commands ###
