"""Remove Application.start/update_time

Revision ID: f21e9e1db760
Revises: da554f1ffff9
Create Date: 2022-01-10 16:20:49.175008

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f21e9e1db760"
down_revision = "da554f1ffff9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "updated_time")
    op.drop_column("application", "start_time")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application",
        sa.Column(
            "start_time", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "application",
        sa.Column(
            "updated_time", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
