"""add unique constraint for benefit years

Revision ID: 2e18eb788bbe
Revises: e294fb147db0
Create Date: 2022-04-04 23:09:01.047660

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e18eb788bbe"
down_revision = "e294fb147db0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uix_employee_id_start_date", "benefit_year", ["employee_id", "start_date"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uix_employee_id_start_date", table_name="benefit_year")
    # ### end Alembic commands ###
