"""Add employer_id column to dua_reporting_unit

Revision ID: 4bd14f975de1
Revises: 615482bbbbd2
Create Date: 2022-03-21 18:22:10.492312

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4bd14f975de1"
down_revision = "615482bbbbd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dua_reporting_unit", sa.Column("employer_id", postgresql.UUID(as_uuid=True), nullable=True)
    )

    # set new employer_id column from organization_unit
    op.execute(
        "UPDATE dua_reporting_unit SET employer_id = (SELECT organization_unit.employer_id FROM dua_reporting_unit JOIN organization_unit USING (organization_unit_id) LIMIT 1)"
    )

    op.drop_constraint("dua_reporting_unit_dua_id_key", "dua_reporting_unit", type_="unique")
    op.create_unique_constraint(
        "uix_dua_reporting_unit_dia_id_employer_id", "dua_reporting_unit", ["dua_id", "employer_id"]
    )
    op.create_foreign_key(None, "dua_reporting_unit", "employer", ["employer_id"], ["employer_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "dua_reporting_unit", type_="foreignkey")  # type: ignore
    op.drop_constraint("dua_reporting_unit_dua_id_key", "dua_reporting_unit", type_="unique")
    op.create_unique_constraint("dua_reporting_unit_dua_id_key", "dua_reporting_unit", ["dua_id"])
    op.drop_column("dua_reporting_unit", "employer_id")
    # ### end Alembic commands ###
