"""adding column irs_submission_date to pfml1099 table

Revision ID: bb297dde715e
Revises: 6d2836a10c85
Create Date: 2022-03-04 15:39:23.030337

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bb297dde715e"
down_revision = "6d2836a10c85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pfml_1099", sa.Column("irs_submission_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pfml_1099", "irs_submission_date")
    # ### end Alembic commands ###
