"""Add back Application.start/update_time

Revision ID: 615070e6a585
Revises: 4f94ce2880fd
Create Date: 2022-01-19 19:39:51.696140

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "615070e6a585"
down_revision = "5eed6252f2a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application", sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column(
        "application", sa.Column("updated_time", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "updated_time")
    op.drop_column("application", "start_time")
    # ### end Alembic commands ###
