"""Add back and deprecate Application.start/update_time

Revision ID: c76d8f0aa8c6
Revises: 4f94ce2880fd
Create Date: 2022-01-19 22:09:10.610671

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c76d8f0aa8c6"
down_revision = "4f94ce2880fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application", sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column(
        "application", sa.Column("updated_time", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "updated_time")
    op.drop_column("application", "start_time")
    # ### end Alembic commands ###
