"""Create holiday table

Revision ID: b9e3f491eba2
Revises: dcb69fd878da
Create Date: 2022-03-15 12:56:48.237173

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b9e3f491eba2"
down_revision = "dcb69fd878da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holiday",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("holiday_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("holiday_name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("holiday_id"),
    )
    op.create_index(op.f("ix_holiday_date"), "holiday", ["date"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_holiday_date"), table_name="holiday")
    op.drop_table("holiday")
    # ### end Alembic commands ###
