"""Add additional user not found info

Revision ID: bc387ccf1f93
Revises: b9e3f491eba2
Create Date: 2022-03-28 21:05:40.481606

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bc387ccf1f93"
down_revision = "b9e3f491eba2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "additional_user_not_found_info",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "additional_user_not_found_info_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("application_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("date_of_hire", sa.Date(), nullable=True),
        sa.Column("is_withholding_tax", sa.Boolean(), nullable=True),
        sa.Column("recently_acquired_or_merged", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.application_id"],
        ),
        sa.PrimaryKeyConstraint("additional_user_not_found_info_id"),
    )
    op.create_index(
        op.f("ix_additional_user_not_found_info_application_id"),
        "additional_user_not_found_info",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_additional_user_not_found_info_application_id"),
        table_name="additional_user_not_found_info",
    )
    op.drop_table("additional_user_not_found_info")
    # ### end Alembic commands ###
