"""Add 1099 request table

Revision ID: b0af0d4f18b3
Revises: 50c0a1e47747
Create Date: 2022-01-26 13:50:37.015985

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b0af0d4f18b3"
down_revision = "50c0a1e47747"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pfml_1099_request",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("pfml_1099_request_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("correction_ind", sa.Boolean(), nullable=False),
        sa.Column("pfml_1099_batch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.employee_id"]),
        sa.ForeignKeyConstraint(["pfml_1099_batch_id"], ["pfml_1099_batch.pfml_1099_batch_id"]),
        sa.PrimaryKeyConstraint("pfml_1099_request_id"),
    )
    op.create_index(
        op.f("ix_pfml_1099_request_employee_id"), "pfml_1099_request", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_pfml_1099_request_pfml_1099_batch_id"),
        "pfml_1099_request",
        ["pfml_1099_batch_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pfml_1099_request_pfml_1099_batch_id"), table_name="pfml_1099_request")
    op.drop_index(op.f("ix_pfml_1099_request_employee_id"), table_name="pfml_1099_request")
    op.drop_table("pfml_1099_request")
    # ### end Alembic commands ###
