"""add PaymentRelevantParty lookup table

Revision ID: 6d2836a10c85
Revises: cdb56bf0decf
Create Date: 2022-02-25 13:25:06.336564

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d2836a10c85"
down_revision = "cdb56bf0decf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_payment_relevant_party",
        sa.Column("payment_relevant_party_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("payment_relevant_party_description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("payment_relevant_party_id"),
    )
    op.add_column("payment", sa.Column("payment_relevant_party_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_payment_payment_relevant_party",
        "payment",
        "lk_payment_relevant_party",
        ["payment_relevant_party_id"],
        ["payment_relevant_party_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_payment_payment_relevant_party", "payment", type_="foreignkey")
    op.drop_column("payment", "payment_relevant_party_id")
    op.drop_table("lk_payment_relevant_party")
    # ### end Alembic commands ###
