"""Add ssn fein max update attempts

Revision ID: 8e0745846466
Revises: 615482bbbbd2
Create Date: 2022-03-24 14:57:33.146425

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8e0745846466"
down_revision = "615482bbbbd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    # Manually added server_default="0"
    op.add_column(
        "application", sa.Column("nbr_of_retries", sa.Integer(), nullable=False, server_default="0")
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "nbr_of_retries")
    # ### end Alembic commands ###
