"""Add Import log report queue table

Revision ID: ece21b10fccd
Revises: f987822e09cc
Create Date: 2022-03-10 11:59:42.079488

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ece21b10fccd"
down_revision = "f987822e09cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_log_report_queue",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("import_log_report_queue_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("import_log_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_log_id"], ["import_log.import_log_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("import_log_report_queue_id"),
    )
    op.create_index(
        op.f("ix_import_log_report_queue_import_log_id"),
        "import_log_report_queue",
        ["import_log_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_import_log_report_queue_import_log_id"), table_name="import_log_report_queue"
    )
    op.drop_table("import_log_report_queue")
    # ### end Alembic commands ###
