"""API-2260: Add business net amount to payment details

Revision ID: da554f1ffff9
Revises: b83ecbdc3ab2
Create Date: 2022-01-04 20:55:31.494618

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "da554f1ffff9"
down_revision = "b83ecbdc3ab2"
branch_labels = None
depends_on = None


def upgrade():
    # Create the business net amount column as nullable
    op.add_column("payment_details", sa.Column("business_net_amount", sa.Numeric(), nullable=True))

    # Do an update to duplicate the amount column over
    op.execute("UPDATE payment_details SET business_net_amount = amount")

    # Alter the business net amount column to be not nullable
    op.alter_column(
        "payment_details", "business_net_amount", existing_type=sa.Numeric(), nullable=False
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_details", "business_net_amount")
    # ### end Alembic commands ###
