"""PAY-43:Add new table for 1099 Request Extract

Revision ID: f89a0e06fb92
Revises: da554f1ffff9
Create Date: 2022-01-11 14:05:38.854468

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import massgov.pfml.db.models.common as ua

# revision identifiers, used by Alembic.
revision = "f89a0e06fb92"
down_revision = "da554f1ffff9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fineos_extract_vbi_1099_data_som",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("vbi_1099_data_som_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("firstnames", sa.Text(), nullable=True),
        sa.Column("lastname", sa.Text(), nullable=True),
        sa.Column("customerno", sa.Text(), nullable=True),
        sa.Column("packeddata", ua.XMLType(), nullable=True),
        sa.Column("documenttype", sa.Text(), nullable=True),
        sa.Column("c", sa.Text(), nullable=True),
        sa.Column("reference_file_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("fineos_extract_import_log_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["fineos_extract_import_log_id"], ["import_log.import_log_id"]),
        sa.ForeignKeyConstraint(["reference_file_id"], ["reference_file.reference_file_id"]),
        sa.PrimaryKeyConstraint("vbi_1099_data_som_id"),
    )
    op.create_index(
        op.f("ix_fineos_extract_vbi_1099_data_som_fineos_extract_import_log_id"),
        "fineos_extract_vbi_1099_data_som",
        ["fineos_extract_import_log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fineos_extract_vbi_1099_data_som_reference_file_id"),
        "fineos_extract_vbi_1099_data_som",
        ["reference_file_id"],
        unique=False,
    )
    op.create_index(
        "ix_vbi_1099_data_som_import_log_id_customerno",
        "fineos_extract_vbi_1099_data_som",
        ["fineos_extract_import_log_id", "customerno"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_vbi_1099_data_som_import_log_id_customerno",
        table_name="fineos_extract_vbi_1099_data_som",
    )
    op.drop_index(
        op.f("ix_fineos_extract_vbi_1099_data_som_reference_file_id"),
        table_name="fineos_extract_vbi_1099_data_som",
    )
    op.drop_index(
        op.f("ix_fineos_extract_vbi_1099_data_som_fineos_extract_import_log_id"),
        table_name="fineos_extract_vbi_1099_data_som",
    )
    op.drop_table("fineos_extract_vbi_1099_data_som")
    # ### end Alembic commands ###
