"""Include MMArs Links to Employee, Claim and Payment i value

Revision ID: cdb56bf0decf
Revises: ef83be635653
Create Date: 2022-02-25 07:38:22.841401

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cdb56bf0decf"
down_revision = "ef83be635653"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mmars_payment_data", sa.Column("claim_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.add_column(
        "mmars_payment_data", sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.add_column("mmars_payment_data", sa.Column("payment_i_value", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_mmars_payment_data_claim_id"), "mmars_payment_data", ["claim_id"], unique=False
    )
    op.create_index(
        op.f("ix_mmars_payment_data_employee_id"),
        "mmars_payment_data",
        ["employee_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_mmars_payment_data_employee_id",
        "mmars_payment_data",
        "claim",
        ["claim_id"],
        ["claim_id"],
    )
    op.create_foreign_key(
        "fk_mmars_payment_data_claim_id",
        "mmars_payment_data",
        "employee",
        ["employee_id"],
        ["employee_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_mmars_payment_data_employee_id", "mmars_payment_data", type_="foreignkey"
    )
    op.drop_constraint("fk_mmars_payment_data_claim_id", "mmars_payment_data", type_="foreignkey")
    op.drop_index(op.f("ix_mmars_payment_data_employee_id"), table_name="mmars_payment_data")
    op.drop_index(op.f("ix_mmars_payment_data_claim_id"), table_name="mmars_payment_data")
    op.drop_column("mmars_payment_data", "payment_i_value")
    op.drop_column("mmars_payment_data", "employee_id")
    op.drop_column("mmars_payment_data", "claim_id")
    # ### end Alembic commands ###
