"""remove application nickname

Revision ID: 4494638eca87
Revises: b9e3f491eba2
Create Date: 2022-03-24 01:34:35.291631

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4494638eca87"
down_revision = "b9e3f491eba2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "nickname")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application", sa.Column("nickname", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
