"""Remove payment foreign key from mmars table

Revision ID: 669cb17688dd
Revises: ece21b10fccd
Create Date: 2022-03-15 09:33:06.753335

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "669cb17688dd"
down_revision = "ece21b10fccd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mmars_payment_data_payment_id", table_name="mmars_payment_data")
    op.drop_constraint(
        "mmars_payment_data_payment_id_fkey", "mmars_payment_data", type_="foreignkey"
    )
    op.drop_column("mmars_payment_data", "payment_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mmars_payment_data",
        sa.Column("payment_id", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "mmars_payment_data_payment_id_fkey",
        "mmars_payment_data",
        "payment",
        ["payment_id"],
        ["payment_id"],
    )
    op.create_index(
        "ix_mmars_payment_data_payment_id", "mmars_payment_data", ["payment_id"], unique=False
    )
    # ### end Alembic commands ###
