"""add unique constraint for benefit years

Revision ID: c7425fa3402e
Revises: 805818d3b07c
Create Date: 2022-04-08 13:32:34.777324

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "c7425fa3402e"
down_revision = "805818d3b07c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uix_employee_id_start_date", "benefit_year", ["employee_id", "start_date"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uix_employee_id_start_date", table_name="benefit_year")
    # ### end Alembic commands ###
