"""Add user not found submission

Revision ID: 07ca8514b0f5
Revises: 7b183dd23b33
Create Date: 2022-02-02 14:23:53.955655

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "07ca8514b0f5"
down_revision = "7b183dd23b33"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_not_found_submission",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_not_found_submission_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("application_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("employer_fein", sa.Text(), nullable=True),
        sa.Column("employer_name", sa.Text(), nullable=True),
        sa.Column("submitted_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["application_id"], ["application.application_id"],),
        sa.PrimaryKeyConstraint("user_not_found_submission_id"),
    )
    op.create_index(
        op.f("ix_user_not_found_submission_application_id"),
        "user_not_found_submission",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_not_found_submission_application_id"), table_name="user_not_found_submission"
    )
    op.drop_table("user_not_found_submission")
    # ### end Alembic commands ###
