"""Add source_context to importlog

Revision ID: 98f857e4382c
Revises: 3fbc57dc3880
Create Date: 2022-04-06 22:02:49.646714

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "98f857e4382c"
down_revision = "805818d3b07c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("import_log", sa.Column("source_context", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("import_log", "source_context")
    # ### end Alembic commands ###
