"""Allow ChangeRequest.change_request_id to be null

Revision ID: 85c5005ecc8c
Revises: 626ad4463740
Create Date: 2022-04-15 12:36:08.584881

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "85c5005ecc8c"
down_revision = "626ad4463740"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "change_request", "change_request_type_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "change_request", "change_request_type_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
