"""Create 1099 refund backup table.

Revision ID: 5ddd0ba0df83
Revises: f8849c54ed7a
Create Date: 2022-01-03 21:57:06.948886

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5ddd0ba0df83"
down_revision = "f8849c54ed7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pfml_1099_refund_backup",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("pfml_1099_refund_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("pfml_1099_batch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("payment_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("refund_amount", sa.Numeric(), nullable=True),
        sa.Column("refund_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("pfml_1099_refund_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pfml_1099_refund_backup")
    # ### end Alembic commands ###
