"""add unique constraint for benefit years

Revision ID: d1f44773cff6
Revises: e294fb147db0
Create Date: 2022-04-02 01:40:45.897171

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "d1f44773cff6"
down_revision = "e294fb147db0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_employee_id_start_date", "benefit_year", ["employee_id", "start_date"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_employee_id_start_date", "benefit_year", type_="unique")
    # ### end Alembic commands ###
