"""change employer fein data type

Revision ID: e081304c01b0
Revises: a5a12d592f91
Create Date: 2020-04-28 21:24:43.209761

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e081304c01b0"
down_revision = "a5a12d592f91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employer",
        "employer_fein",
        existing_type=sa.INTEGER(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "user", "email_address", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "email_address", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True
    )
    op.alter_column(
        "employer",
        "employer_fein",
        existing_type=sa.Text(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
