-- PFML Claimant Error Report
WITH CLAIMANT_BATCH_TRANSACTIONS AS (
	SELECT
		C.FINEOS_ABSENCE_ID,
		C.ABSENCE_PERIOD_START_DATE,
		C.ABSENCE_PERIOD_END_DATE,
		CT.CLAIM_TYPE_DESCRIPTION,
		E.FINEOS_CUSTOMER_NUMBER,
		FAS.ABSENCE_STATUS_DESCRIPTION,
		SL.OUTCOME,
		ST1.STATE_ID AS CURRENT_STATE_ID,
		ST1.STATE_DESCRIPTION AS CURRENT_STATE
	FROM
		CLAIM C
	LEFT OUTER JOIN EMPLOYEE E ON C.EMPLOYEE_ID = E.EMPLOYEE_ID
	LEFT OUTER JOIN LK_CLAIM_TYPE CT ON CT.CLAIM_TYPE_ID = C.CLAIM_TYPE_ID
	LEFT OUTER JOIN LK_ABSENCE_STATUS FAS ON C.FINEOS_ABSENCE_STATUS_ID = FAS.ABSENCE_STATUS_ID
	INNER JOIN STATE_LOG SL ON C.CLAIM_ID = SL.CLAIM_ID
	INNER JOIN LK_STATE ST1 ON SL.END_STATE_ID = ST1.STATE_ID
WHERE
	SL.IMPORT_LOG_ID = (
		SELECT
			MAX(IMPORT_LOG_ID)
		FROM
			IMPORT_LOG
		WHERE
			SOURCE = 'ClaimantExtractStep')
)
SELECT
	CBT.FINEOS_CUSTOMER_NUMBER "Customer Number",
	CBT.FINEOS_ABSENCE_ID "NTN Number",
    CBT.ABSENCE_STATUS_DESCRIPTION "Absence Status",
    CBT.ABSENCE_PERIOD_START_DATE "Absence Period Start Date", 
    CBT.ABSENCE_PERIOD_END_DATE "Absence Period End Date",
	CBT.OUTCOME ->> 'message' "Error Message",
	json_array_elements(CBT.OUTCOME -> 'validation_container' -> 'validation_issues') ->> 'reason' "Reason",
	json_array_elements(CBT.OUTCOME -> 'validation_container' -> 'validation_issues') ->> 'details' "Details"
FROM
	CLAIMANT_BATCH_TRANSACTIONS CBT
WHERE
	CBT.CURRENT_STATE_ID in(165)
