-- PFML Claimant Error Report
WITH CLAIMANT_BATCH_TRANSACTIONS AS (
    SELECT E.FINEOS_CUSTOMER_NUMBER, E.LAST_NAME, E.FIRST_NAME, 
	       SL.OUTCOME, SL.END_STATE_ID
    FROM STATE_LOG SL
	LEFT OUTER JOIN EMPLOYEE E ON SL.EMPLOYEE_ID = E.EMPLOYEE_ID
	LEFT OUTER JOIN PAYMENT P ON SL.PAYMENT_ID = P.PAYMENT_ID
    WHERE SL.IMPORT_LOG_ID = (SELECT MAX(IMPORT_LOG_ID)
                                            FROM IMPORT_LOG
                                            WHERE SOURCE = 'ClaimantExtractStep'))
SELECT CBT.FINEOS_CUSTOMER_NUMBER "Customer Number",
       CBT.LAST_NAME "Last Name",
       CBT.FIRST_NAME "First Name",
       CBT.OUTCOME::json#>'{message}' result
FROM CLAIMANT_BATCH_TRANSACTIONS CBT
WHERE CBT.END_STATE_ID IN (101)
