WITH FINEOS_TXNS    AS (SELECT CD.ABSENCECASENU, FEP.*
                        FROM FINEOS_EXTRACT_PAYMENT_FULL_SNAPSHOT FEP
                        LEFT OUTER JOIN FINEOS_EXTRACT_VPEI_CLAIM_DETAILS CD ON FEP.I = CD.PEINDEXID
                                                                             AND CD.FINEOS_EXTRACT_IMPORT_LOG_ID = (SELECT MAX(FINEOS_EXTRACT_IMPORT_LOG_ID)
										                                                                            FROM FINEOS_EXTRACT_VPEI_CLAIM_DETAILS CD2
										                                                                            WHERE CD2.PEINDEXID = CD.PEINDEXID)
                        WHERE FEP.FINEOS_EXTRACT_IMPORT_LOG_ID = (SELECT MAX(FINEOS_EXTRACT_IMPORT_LOG_ID)
                                                                  FROM FINEOS_EXTRACT_PAYMENT_FULL_SNAPSHOT)
                          AND FEP.EVENTTYPE = 'PaymentOut'
                          AND CAST(AMOUNT_MONAMT AS DECIMAL) > 0
                          AND CAST(CASE WHEN EXTRACTIONDAT IS NULL THEN PAYMENTDATE 
                                        WHEN EXTRACTIONDAT = '' THEN PAYMENTDATE
                                        ELSE EXTRACTIONDAT END AS DATE) < CAST(DATE_TRUNC('WEEK', CURRENT_DATE) AS DATE)-1),
     FINEOS_CNCL    AS (SELECT CP.*
                        FROM FINEOS_EXTRACT_CANCELLED_PAYMENTS CP
                        WHERE CP.FINEOS_EXTRACT_IMPORT_LOG_ID = (SELECT MAX(FINEOS_EXTRACT_IMPORT_LOG_ID)
                                                                 FROM FINEOS_EXTRACT_CANCELLED_PAYMENTS)),
     FINEOS_RPLC    AS (SELECT RP.*
                        FROM FINEOS_EXTRACT_REPLACED_PAYMENTS RP
                        WHERE RP.FINEOS_EXTRACT_IMPORT_LOG_ID = (SELECT MAX(FINEOS_EXTRACT_IMPORT_LOG_ID)
                                                                 FROM FINEOS_EXTRACT_REPLACED_PAYMENTS)),
     MMARS_TXNS     AS (SELECT SUBSTRING(VENDOR_INVOICE_NO, 19) I, MPD.*
                        FROM MMARS_PAYMENT_DATA MPD),
     MMARS_SUMMARY_TXNS AS (SELECT MT.I MTI, FT.I FTI, FC.I FCI, FR.I FRI, 
                               CAST(FT.AMOUNT_MONAMT AS DECIMAL) FT_AMOUNT,
                               CAST(MT.PYMT_ACTG_LINE_AMOUNT AS DECIMAL) MT_AMOUNT
                        FROM MMARS_TXNS MT
                        LEFT OUTER JOIN FINEOS_TXNS FT ON MT.I = FT.I
                        LEFT OUTER JOIN FINEOS_CNCL FC ON FT.I = FC.I
                        LEFT OUTER JOIN FINEOS_RPLC FR ON FT.I = FR.I),
     CHECK_PAYMENTS AS (SELECT PAYMENT_ID FROM STATE_LOG WHERE END_STATE_ID = 137),
     EFT_PAYMENTS   AS (SELECT PAYMENT_ID FROM STATE_LOG WHERE END_STATE_ID = 139),
     BANK_ERRORS    AS (SELECT PAYMENT_ID FROM STATE_LOG WHERE END_STATE_ID = 182),
     PUB_TXNS       AS (SELECT P.*, TT.PAYMENT_TRANSACTION_TYPE_DESCRIPTION
                        FROM PAYMENT P
                        LEFT OUTER JOIN CHECK_PAYMENTS CP ON P.PAYMENT_ID = CP.PAYMENT_ID
                        LEFT OUTER JOIN EFT_PAYMENTS EFT ON P.PAYMENT_ID = EFT.PAYMENT_ID
                        LEFT OUTER JOIN BANK_ERRORS BE ON P.PAYMENT_ID = BE.PAYMENT_ID
                        LEFT OUTER JOIN LK_PAYMENT_TRANSACTION_TYPE TT ON P.PAYMENT_TRANSACTION_TYPE_ID = TT.PAYMENT_TRANSACTION_TYPE_ID
                        WHERE (CP.PAYMENT_ID IS NOT NULL OR EFT.PAYMENT_ID IS NOT NULL)
						  AND BE.PAYMENT_ID IS NULL
                          AND P.FINEOS_EXTRACTION_DATE < CAST(DATE_TRUNC('WEEK', CURRENT_DATE) AS DATE)-1),
     PUB_SUMMARY_TXNS AS (SELECT PT.FINEOS_PEI_I_VALUE PTI, FT.I FTI, FC.I FCI, FR.I FRI,
                                  CAST(FT.AMOUNT_MONAMT AS DECIMAL) FT_AMOUNT,
                                  CAST(PT.AMOUNT AS DECIMAL) PT_AMOUNT
                           FROM PUB_TXNS PT
                           LEFT OUTER JOIN FINEOS_TXNS FT ON PT.FINEOS_PEI_I_VALUE = FT.I
                           LEFT OUTER JOIN FINEOS_CNCL FC ON FT.I = FC.I
                           LEFT OUTER JOIN FINEOS_RPLC FR ON FT.I = FR.I),
     PMTS AS           (SELECT P.*
			            FROM PAYMENT P
			            WHERE P.FINEOS_EXTRACT_IMPORT_LOG_ID = (SELECT MAX(P2.FINEOS_EXTRACT_IMPORT_LOG_ID)
													            FROM PAYMENT P2
													            WHERE P2.FINEOS_PEI_I_VALUE = P.FINEOS_PEI_I_VALUE)),
     FINEOS_SUMMARY_TXNS AS (SELECT PT.PAYMENT_ID PUB_PAYMENT_ID, FC.CANELLED_PAYMENT_ID CANELLED_PAYMENT_ID, FR.REPLACED_PAYMENT_ID REPLACED_PAYMENT_ID,
                                    MT.MMARS_PAYMENT_DATA_ID MMARS_PAYMENT_DATA_ID, FT.TRANSACTIONST TRANSACTION_STATUS, PT.PAYMENT_TRANSACTION_TYPE_DESCRIPTION
                             FROM FINEOS_TXNS FT 
                             LEFT OUTER JOIN PUB_TXNS PT ON PT.FINEOS_PEI_I_VALUE = FT.I
                             LEFT OUTER JOIN MMARS_TXNS MT ON MT.I = FT.I
                             LEFT OUTER JOIN FINEOS_CNCL FC ON FT.I = FC.I
                             LEFT OUTER JOIN FINEOS_RPLC FR ON FT.I = FR.I)
SELECT 'MMARS Payment Reconciliation - Detail Transactions (through ' || CAST(DATE_TRUNC('WEEK', CURRENT_DATE) AS DATE)-2 || ')' TRANSACTION_DESCRIPTION, 
       NULL NTN, NULL I, NULL PAYMENT_DATE, NULL PERIOD_START_DATE, NULL PERIOD_END_DATE, NULL AMOUNT, NULL PAYMENT_TRANSACTION_TYPE_DESCRIPTION
UNION ALL
SELECT '* ' || 
       CASE WHEN FT.I IS NOT NULL AND FC.I IS NULL AND FR.I IS NULL AND CAST(FT.AMOUNT_MONAMT AS DECIMAL) <> CAST(MT.PYMT_ACTG_LINE_AMOUNT AS DECIMAL) THEN 'Unmatching FINEOS Payments (Differing Amounts)' 
            WHEN FT.I IS NULL THEN 'Unmatching FINEOS Payments' 
            WHEN FC.I IS NOT NULL AND FT.I IS NOT NULL THEN 'Matching FINEOS Cancelled Payments' 
            WHEN FR.I IS NOT NULL AND FT.I IS NOT NULL THEN 'Matching FINEOS Replaced Payments' 
       END TRANSACTION_DESCRIPTION, MT.VENDOR_INVOICE_NO NTN, MT.I I,
       TO_CHAR(WARRANT_SELECT_DATE, 'MM/DD/YYYY') PAYMENT_DATE, TO_CHAR(PYMT_SERVICE_FROM_DATE, 'MM/DD/YYYY') PERIOD_START_DATE, TO_CHAR(PYMT_SERVICE_TO_DATE, 'MM/DD/YYYY') PERIOD_END_DATE, CAST(PYMT_ACTG_LINE_AMOUNT AS TEXT) AMOUNT, '' PAYMENT_TRANSACTION_TYPE_DESCRIPTION
FROM MMARS_TXNS MT
LEFT OUTER JOIN FINEOS_TXNS FT ON MT.I = FT.I
LEFT OUTER JOIN FINEOS_CNCL FC ON FT.I = FC.I
LEFT OUTER JOIN FINEOS_RPLC FR ON FT.I = FR.I
WHERE (FT.I IS NOT NULL AND FC.I IS NULL AND FR.I IS NULL AND CAST(FT.AMOUNT_MONAMT AS DECIMAL) <> CAST(MT.PYMT_ACTG_LINE_AMOUNT AS DECIMAL))
   OR (FT.I IS NULL)
   OR (FC.I IS NOT NULL AND FT.I IS NOT NULL)
   OR (FR.I IS NOT NULL AND FT.I IS NOT NULL)
UNION ALL
SELECT 'PUB Payment Reconciliation - Detail Transactions (through ' || CAST(DATE_TRUNC('WEEK', CURRENT_DATE) AS DATE)-2 || ')' TRANSACTION_DESCRIPTION, 
       NULL NTN, NULL I, NULL PAYMENT_DATE, NULL PERIOD_START_DATE, NULL PERIOD_END_DATE, NULL AMOUNT, NULL PAYMENT_TRANSACTION_TYPE_DESCRIPTION
UNION ALL
SELECT '** ' || 
       CASE WHEN FT.I IS NOT NULL AND FC.I IS NULL AND FR.I IS NULL AND CAST(FT.AMOUNT_MONAMT AS DECIMAL) <> CAST(PT.AMOUNT AS DECIMAL) THEN 'Unmatching FINEOS Payments (Differing Amounts)' 
            WHEN FT.I IS NULL THEN 'Unmatching FINEOS Payments' 
            WHEN FC.I IS NOT NULL AND FT.I IS NOT NULL THEN 'Matching FINEOS Cancelled Payments' 
            WHEN FR.I IS NOT NULL AND FT.I IS NOT NULL THEN 'Matching FINEOS Replaced Payments' 
       END TRANSACTION_DESCRIPTION, CL.FINEOS_ABSENCE_ID NTN, PT.FINEOS_PEI_I_VALUE I,
       TO_CHAR(PT.PAYMENT_DATE, 'MM/DD/YYYY') PAYMENT_DATE, TO_CHAR(PT.PERIOD_START_DATE, 'MM/DD/YYYY') PERIOD_START_DATE, TO_CHAR(PT.PERIOD_END_DATE, 'MM/DD/YYYY') PERIOD_END_DATE, CAST(PT.AMOUNT AS TEXT) AMOUNT, PT.PAYMENT_TRANSACTION_TYPE_DESCRIPTION PAYMENT_TRANSACTION_TYPE_DESCRIPTION
FROM PUB_TXNS PT
INNER JOIN CLAIM CL ON PT.CLAIM_ID = CL.CLAIM_ID
LEFT OUTER JOIN FINEOS_TXNS FT ON PT.FINEOS_PEI_I_VALUE = FT.I
LEFT OUTER JOIN FINEOS_CNCL FC ON FT.I = FC.I
LEFT OUTER JOIN FINEOS_RPLC FR ON FT.I = FR.I
WHERE (FT.I IS NOT NULL AND FC.I IS NULL AND FR.I IS NULL AND CAST(FT.AMOUNT_MONAMT AS DECIMAL) <> CAST(PT.AMOUNT AS DECIMAL))
   OR (FT.I IS NULL)
   OR (FC.I IS NOT NULL AND FT.I IS NOT NULL)
   OR (FR.I IS NOT NULL AND FT.I IS NOT NULL)
UNION ALL
SELECT 'FINEOS Payment Reconciliation (through ' || CAST(DATE_TRUNC('WEEK', CURRENT_DATE) AS DATE)-2 || ')' TRANSACTION_DESCRIPTION, 
       NULL NTN, NULL I, NULL PAYMENT_DATE, NULL PERIOD_START_DATE, NULL PERIOD_END_DATE, NULL AMOUNT, NULL PAYMENT_TRANSACTION_TYPE_DESCRIPTION
UNION ALL
SELECT '*** ' || FT.TRANSACTIONST TRANSACTION_DESCRIPTION , FT.ABSENCECASENU NTN, FT.I,
       TO_CHAR(TO_DATE(FT.PAYMENTDATE, 'YYYY-MM-DD HH24:MI:SS'), 'MM/DD/YYYY') PAYMENT_DATE, TO_CHAR(P.PERIOD_START_DATE, 'YYYY-MM-DD') PERIOD_START_DATE, TO_CHAR(P.PERIOD_END_DATE, 'YYYY-MM-DD') PERIOD_END_DATE, CAST(FT.AMOUNT_MONAMT AS TEXT) AMOUNT, '' PAYMENT_TRANSACTION_TYPE_DESCRIPTION
FROM FINEOS_TXNS FT 
LEFT OUTER JOIN PMTS P ON P.FINEOS_PEI_I_VALUE = FT.I
LEFT OUTER JOIN PUB_TXNS PT ON PT.FINEOS_PEI_I_VALUE = FT.I
LEFT OUTER JOIN MMARS_TXNS MT ON MT.I = FT.I
LEFT OUTER JOIN FINEOS_CNCL FC ON FT.I = FC.I
LEFT OUTER JOIN FINEOS_RPLC FR ON FT.I = FR.I
WHERE MT.MMARS_PAYMENT_DATA_ID IS NULL 
  AND PT.PAYMENT_ID IS NULL 
  AND FR.REPLACED_PAYMENT_ID IS NULL
  AND FC.CANELLED_PAYMENT_ID IS NULL
