-- PFML Payment Summary Report
WITH PAYMENT_BATCH_TRANSACTIONS AS (SELECT P.FINEOS_EXTRACT_IMPORT_LOG_ID, P.PAYMENT_ID, P.PERIOD_START_DATE, P.PERIOD_END_DATE, P.PAYMENT_DATE, P.AMOUNT,
                                           C.FINEOS_ABSENCE_ID, C.ABSENCE_PERIOD_START_DATE, C.ABSENCE_PERIOD_END_DATE,
                                           P.CLAIM_TYPE_ID, CT.CLAIM_TYPE_DESCRIPTION, E.FINEOS_CUSTOMER_NUMBER, FAS.ABSENCE_STATUS_DESCRIPTION,
                                           P.FINEOS_PEI_C_VALUE, P.FINEOS_PEI_I_VALUE, P.FINEOS_EXTRACTION_DATE,
                                           LAG(ST1.STATE_DESCRIPTION) OVER(PARTITION BY P.PAYMENT_ID ORDER BY SL.STARTED_AT) AS PRIOR_STATE,
                                           SL.OUTCOME,
                                           ST1.STATE_ID AS CURRENT_STATE_ID,
                                           ST1.STATE_DESCRIPTION AS CURRENT_STATE,
                                           LEAD(ST1.STATE_DESCRIPTION) OVER(PARTITION BY P.PAYMENT_ID ORDER BY SL.STARTED_AT) AS NEXT_STATE,
                                           SL.STARTED_AT AS EFFECTIVE_START,
                                           COALESCE(LEAD(SL.STARTED_AT) OVER(PARTITION BY P.PAYMENT_ID ORDER BY SL.STARTED_AT), DATE '9999-12-31') AS EFFECTIVE_END,
                                           CASE WHEN LEAD(SL.STARTED_AT) OVER(PARTITION BY P.PAYMENT_ID ORDER BY SL.STARTED_AT) IS NULL THEN 'Y' ELSE 'N' END AS IS_CURRENT
                                    FROM PAYMENT P
                                    LEFT OUTER JOIN CLAIM C ON P.CLAIM_ID = C.CLAIM_ID
                                    LEFT OUTER JOIN LK_CLAIM_TYPE CT ON CT.CLAIM_TYPE_ID = P.CLAIM_TYPE_ID
                                    LEFT OUTER JOIN LK_ABSENCE_STATUS FAS ON C.FINEOS_ABSENCE_STATUS_ID = FAS.ABSENCE_STATUS_ID
                                    LEFT OUTER JOIN EMPLOYEE E ON P.EMPLOYEE_ID = E.EMPLOYEE_ID
                                    INNER JOIN STATE_LOG SL ON P.PAYMENT_ID = SL.PAYMENT_ID
                                    INNER JOIN LK_STATE ST1 ON SL.END_STATE_ID = ST1.STATE_ID)
SELECT 'Withholding Type' WITHHOLDING_TYPE, 
       'Current Day (' || CURRENT_DATE || ')' CURR_DAY, 
                 'Week to Date (' || CAST(DATE_TRUNC('WEEK', CURRENT_DATE) AS DATE) || ')' WTD, 
                 'Month to Date (' || CAST(DATE_TRUNC('MONTH', CURRENT_DATE) AS DATE) || ')' MTD, 
                 'Year to Date (' || CAST(DATE_TRUNC('YEAR', CURRENT_DATE) AS DATE) || ')' YTD
UNION ALL
SELECT 'Federal Tax' WITHHOLDING_TYPE, 
       TO_CHAR(SUM(CASE WHEN PBT.CURRENT_STATE_ID IN (208) AND CAST(IL.START AS DATE) = CURRENT_DATE THEN PBT.AMOUNT ELSE 0 END), '$999,999,990D99') CURR_DAY,
       TO_CHAR(SUM(CASE WHEN PBT.CURRENT_STATE_ID IN (208) AND CAST(IL.START AS DATE) >= DATE_TRUNC('WEEK', CURRENT_DATE) THEN PBT.AMOUNT ELSE 0 END), '$999,999,990D99') WTD,
       TO_CHAR(SUM(CASE WHEN PBT.CURRENT_STATE_ID IN (208) AND CAST(IL.START AS DATE) >= DATE_TRUNC('MONTH', CURRENT_DATE) THEN PBT.AMOUNT ELSE 0 END), '$999,999,990D99') MTD,
       TO_CHAR(SUM(CASE WHEN PBT.CURRENT_STATE_ID IN (208) AND CAST(IL.START AS DATE) >= DATE_TRUNC('YEAR', CURRENT_DATE) THEN PBT.AMOUNT ELSE 0 END), '$999,999,990D99') YTD
FROM PAYMENT_BATCH_TRANSACTIONS PBT 
INNER JOIN IMPORT_LOG IL ON PBT.FINEOS_EXTRACT_IMPORT_LOG_ID = IL.IMPORT_LOG_ID
UNION ALL
SELECT 'State Tax' WITHHOLDING_TYPE, 
       TO_CHAR(SUM(CASE WHEN PBT.CURRENT_STATE_ID IN (207) AND CAST(IL.START AS DATE) = CURRENT_DATE THEN PBT.AMOUNT ELSE 0 END), '$999,999,990D99') CURR_DAY,
       TO_CHAR(SUM(CASE WHEN PBT.CURRENT_STATE_ID IN (207) AND CAST(IL.START AS DATE) >= DATE_TRUNC('WEEK', CURRENT_DATE) THEN PBT.AMOUNT ELSE 0 END), '$999,999,990D99') WTD,
       TO_CHAR(SUM(CASE WHEN PBT.CURRENT_STATE_ID IN (207) AND CAST(IL.START AS DATE) >= DATE_TRUNC('MONTH', CURRENT_DATE) THEN PBT.AMOUNT ELSE 0 END), '$999,999,990D99') MTD,
       TO_CHAR(SUM(CASE WHEN PBT.CURRENT_STATE_ID IN (207) AND CAST(IL.START AS DATE) >= DATE_TRUNC('YEAR', CURRENT_DATE) THEN PBT.AMOUNT ELSE 0 END), '$999,999,990D99') YTD
FROM PAYMENT_BATCH_TRANSACTIONS PBT 
INNER JOIN IMPORT_LOG IL ON PBT.FINEOS_EXTRACT_IMPORT_LOG_ID = IL.IMPORT_LOG_ID
