-- PFML Weekly Payment Summary Report
WITH CHECK_PAYMENTS AS (
		SELECT PAYMENT_ID, ENDED_AT PAYMENT_DATE FROM STATE_LOG WHERE END_STATE_ID = 137),
	EFT_PAYMENTS AS 
		(SELECT PAYMENT_ID, ENDED_AT PAYMENT_DATE FROM STATE_LOG WHERE END_STATE_ID = 139),
	BANK_ERRORS AS 
		(SELECT PAYMENT_ID, ENDED_AT PAYMENT_DATE FROM STATE_LOG WHERE END_STATE_ID = 182),
	FED_WTHDNGS AS 
		(SELECT PAYMENT_ID, ENDED_AT PAYMENT_DATE FROM STATE_LOG WHERE END_STATE_ID = 208),
	ST_WTHDNGS AS 
		(SELECT PAYMENT_ID, ENDED_AT PAYMENT_DATE FROM STATE_LOG WHERE END_STATE_ID = 207),
	TXNS AS 
		(SELECT CP.PAYMENT_ID, CP.PAYMENT_DATE, P.AMOUNT CHECK_AMOUNT, 
		0 EFT_AMOUNT,0 FED_WITHHOLDING_AMOUNT, 0 ST_WITHHOLDING_AMOUNT,
		0 CANCEL_AMOUNT 
		FROM PAYMENT P
		INNER JOIN CHECK_PAYMENTS CP ON P.PAYMENT_ID = CP.PAYMENT_ID UNION ALL
		SELECT EP.PAYMENT_ID,EP.PAYMENT_DATE, 0 CHECK_AMOUNT, P.AMOUNT EFT_AMOUNT, 0 FED_WITHHOLDING_AMOUNT,0 ST_WITHHOLDING_AMOUNT, 
		0 CANCEL_AMOUNT
		FROM PAYMENT P
		INNER JOIN EFT_PAYMENTS EP ON P.PAYMENT_ID = EP.PAYMENT_ID UNION ALL 
		SELECT FW.PAYMENT_ID, FW.PAYMENT_DATE, 0 CHECK_AMOUNT, 0 EFT_AMOUNT,
		P.AMOUNT FED_WITHHOLDING_AMOUNT, 0 ST_WITHHOLDING_AMOUNT, 
		0 CANCEL_AMOUNT
		FROM PAYMENT P
		INNER JOIN FED_WTHDNGS FW ON P.PAYMENT_ID = FW.PAYMENT_ID UNION ALL 
		SELECT SW.PAYMENT_ID, SW.PAYMENT_DATE, 0 CHECK_AMOUNT, 0 EFT_AMOUNT, 
		0 FED_WITHHOLDING_AMOUNT,P.AMOUNT ST_WITHHOLDING_AMOUNT, 
		0 CANCEL_AMOUNT FROM PAYMENT P
		INNER JOIN ST_WTHDNGS SW ON P.PAYMENT_ID = SW.PAYMENT_ID UNION ALL 
		SELECT BE.PAYMENT_ID, BE.PAYMENT_DATE, 0 CHECK_AMOUNT, 0 EFT_AMOUNT, 
		0 FED_WITHHOLDING_AMOUNT,0 ST_WITHHOLDING_AMOUNT, P.AMOUNT CANCEL_AMOUNT FROM PAYMENT P 
		INNER JOIN BANK_ERRORS BE ON P.PAYMENT_ID = BE.PAYMENT_ID
		)
	SELECT CAST(DATE_TRUNC('WEEK', T.PAYMENT_DATE) + INTERVAL '5 DAY' AS DATE)
		"Week End Date",CT.CLAIM_TYPE_DESCRIPTION "Absence Case Type",
		TO_CHAR(SUM(T.CHECK_AMOUNT + T.EFT_AMOUNT + T.FED_WITHHOLDING_AMOUNT + 
		T.ST_WITHHOLDING_AMOUNT), '$9,999,999,999,990.00') "Payment Amount",
		TO_CHAR(SUM(T.CHECK_AMOUNT), '$9,999,999,999,990.00') 
		AS "Check Payment Amount",
		TO_CHAR(SUM(T.EFT_AMOUNT), '$9,999,999,999,990.00')
		AS "EFT Payment Amount",
		TO_CHAR(SUM(T.FED_WITHHOLDING_AMOUNT), '$9,999,999,999,990.00') 
		AS "Federal Withholdings",
		TO_CHAR(SUM(T.ST_WITHHOLDING_AMOUNT), '$9,999,999,999,990.00') 
		AS "State Withholdings",
		TO_CHAR(SUM(T.CANCEL_AMOUNT), '$9,999,999,999,990.00') 
		AS "Payment Error Amount"
		FROM TXNS T
		INNER JOIN PAYMENT P ON T.PAYMENT_ID = P.PAYMENT_ID 
		LEFT OUTER JOIN LK_CLAIM_TYPE CT ON CT.CLAIM_TYPE_ID = P.CLAIM_TYPE_ID
		WHERE P.FINEOS_EXTRACTION_DATE >= '2021-07-01'
		AND CAST(DATE_TRUNC('WEEK', T.PAYMENT_DATE) + INTERVAL '5 DAY'
		AS DATE) <= CURRENT_DATE
		GROUP BY CAST(DATE_TRUNC('WEEK', T.PAYMENT_DATE) + INTERVAL '5 DAY' 
		AS DATE),
		CT.CLAIM_TYPE_DESCRIPTION  ORDER BY CAST(DATE_TRUNC('WEEK', T.PAYMENT_DATE) + INTERVAL '5 DAY' AS DATE)