version: "3.8"

services:
  mass-pfml-db:
    image: postgres:12.4-alpine
    container_name: "mass-pfml-db"
    platform: linux/amd64 # Fix running on Apple silicon 
    ports:
      - "5432:5432"
    # Docs for options to the postgres server command:
    # https://www.postgresql.org/docs/current/app-postgres.html
    command: postgres -c "log_lock_waits=on" -N 1000 -c "fsync=off"
    environment:
      - POSTGRES_DB=pfml
      - POSTGRES_USER=pfml
      - POSTGRES_PASSWORD=secret123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - mass-pfml-db
  mass-pfml-api:
    build:
      context: .
      target: dev
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-nodummy}
    image: mass-pfml-api:dev
    container_name: mass-pfml-api
    init: true
    links:
      - mass-pfml-db
    platform: linux/amd64 # Fix running on Apple silicon 
    ports:
      - "1550:1550"
    environment:
      # Misc. non-app settings
      - TERM=${TERM:-xterm-256color}
      - 'PS1=${DOCKER_PS1:-[docker] \w: }'
      - 'LSCOLORS=${DOCKER_LSCOLORS:- }'
      - RUN_CMD_OPT=NATIVE
      - ENABLE_FULL_ERROR_LOGS=1
      - PYTHONPATH=/app/
      # Application configuration
      - ENVIRONMENT=local
      - DB_HOST=mass-pfml-db
      - DB_NAME=pfml
      - DB_ADMIN_USERNAME=pfml
      - DB_ADMIN_PASSWORD=secret123
      - DB_USERNAME=pfml_api
      - DB_PASSWORD=secret123
      - DB_NESSUS_PASSWORD=nessussecret123
      - CORS_ORIGINS=http://localhost:3000
      - COGNITO_USER_POOL_KEYS_URL=file:///app/jwks.json
      # Stage Cognito resource
      - COGNITO_USER_POOL_ID=us-east-1_HpL4XslLg
      - COGNITO_USER_POOL_CLIENT_ID=10rjcp71r8bnk4459c67bn18t8
      - DASHBOARD_PASSWORD=secret123
      - LOGGING_LEVEL=massgov.pfml.fineos.fineos_client=DEBUG
      - ENABLE_EMPLOYEE_ENDPOINTS=1
      - FOLDER_PATH=dor_mock
      - FINEOS_FOLDER_PATH=fineos_mock
      # Enable this variable after initial full load
      # - ELIGIBILITY_FEED_MODE=updates
      # Enable this variable to configure /rmv-check
      - RMV_CHECK_BEHAVIOR=fully_mocked
      - RMV_CHECK_MOCK_SUCCESS=1
      # Enable these variables to use a real FINEOS API instead of a mock:
      # - FINEOS_CLIENT_CUSTOMER_API_URL=https://idt-api.masspfml.fineos.com/customerapi/
      # - FINEOS_CLIENT_WSCOMPOSER_API_URL=https://idt-api.masspfml.fineos.com/integration-services/wscomposer/
      # - FINEOS_CLIENT_GROUP_CLIENT_API_URL=https://idt-api.masspfml.fineos.com/groupclientapi/
      # - FINEOS_CLIENT_INTEGRATION_SERVICES_API_URL=https://idt-api.masspfml.fineos.com/integration-services/
      # - FINEOS_CLIENT_OAUTH2_URL=https://idt-api.masspfml.fineos.com/oauth2/token
      # - FINEOS_CLIENT_OAUTH2_CLIENT_ID=...
      # - FINEOS_CLIENT_OAUTH2_CLIENT_SECRET=...
      # - OAUTHLIB_INSECURE_TRANSPORT=1
      # Disable this variable and set the following three variables to use a real Service Now API instead of a mock:
      - ENABLE_MOCK_SERVICE_NOW_CLIENT=1
      # - SERVICE_NOW_BASE_URL=...
      # - SERVICE_NOW_USERNAME=...
      # - SERVICE_NOW_PASSWORD=...
      - PORTAL_BASE_URL=https://paidleave.mass.gov
      - ENABLE_APPLICATION_FRAUD_CHECK=0
      # Payments env vars
      # - FINEOS_VENDOR_MAX_HISTORY_DATE=2021-01-01
      # - FINEOS_PAYMENT_MAX_HISTORY_DATE=2021-01-01
      # - PAYMENTS_GAX_BIEVNT_EMAIL=
      # - PAYMENTS_DFML_BUSINESS_OPERATIONS_EMAIL=
      - AGENCY_REDUCTIONS_EMAIL_ADDRESS=EOL-DL-DFML-Agency-Reductions@mass.gov
      - DFML_PROJECT_MANAGER_EMAIL_ADDRESS=
      - PFML_EMAIL_ADDRESS=PFML_DoNotReply@eol.mass.gov
      - BOUNCE_FORWARDING_EMAIL_ADDRESS=PFML_DoNotReply@eol.mass.gov
      # Uncomment and set these in order to run the FINEOS and CTR ECS tasks locally with real S3
      # You'll also need to configure the mount for your ~/.aws/credentials in
      # docker-compose.override.yml in order for this to work.
      #- FINEOS_DATA_EXPORT_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/fake-fineos-export/
      #- FINEOS_DATA_IMPORT_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/fake-fineos-import/
      #- PFML_CTR_INBOUND_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/ctr/inbound
      #- PFML_CTR_OUTBOUND_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/ctr/outbound
      #- PFML_FINEOS_INBOUND_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/cps/inbound
      #- PFML_FINEOS_OUTBOUND_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/cps/outbound
      #- PFML_ERROR_REPORTS_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/error-reports/outbound
      #- AWS_PROFILE=AWS-498823821309-Infrastructure-Admin_profile

    networks:
      main:
        aliases:
          - mass-pfml-api
    depends_on:
      - "mass-pfml-db"

networks:
  main:

volumes:
  pgdata:
