version: "3.8"

services:
  sftp:
    image: atmoz/sftp
    container_name: "mass-pfml-sftp"
    ports:
      - "2222:22"
    command: foo:pass:1001
    volumes:
      - ./local_sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./local_sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ./local_sftp/ssh_api_rsa_key.pub:/home/foo/.ssh/keys/ssh_api_rsa_key.pub:ro
      - ./local_sftp/upload:/home/foo/upload
    networks:
      main:
        aliases:
          - mass-pfml-sftp
  mass-pfml-db:
    image: postgres:12.4-alpine
    container_name: "mass-pfml-db"
    platform: linux/amd64 # Fix running on Apple silicon 
    ports:
      - "5432:5432"
    # Docs for options to the postgres server command:
    # https://www.postgresql.org/docs/current/app-postgres.html
    command: postgres -c "log_lock_waits=on" -N 1000 -c "fsync=off"
    environment:
      - POSTGRES_DB=pfml
      - POSTGRES_USER=pfml
      - POSTGRES_PASSWORD=secret123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - mass-pfml-db
  mass-pfml-api:
    build:
      context: .
      target: dev
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-nodummy}
    image: mass-pfml-api:dev
    container_name: mass-pfml-api
    init: true
    links:
      - mass-pfml-db
    platform: linux/amd64 # Fix running on Apple silicon 
    ports:
      - "1550:1550"
    env_file:
      - config/local.env
    environment:
      - TERM=${TERM:-xterm-256color}
      - 'PS1=${DOCKER_PS1:-[docker] \w: }'
      - 'LSCOLORS=${DOCKER_LSCOLORS:- }'
      - ENABLE_FULL_ERROR_LOGS=1
      - PYTHONPATH=/app/

    networks:
      main:
        aliases:
          - mass-pfml-api
    depends_on:
      - "mass-pfml-db"

networks:
  main:

volumes:
  pgdata:
