version: "3.8"

services:
  mass-pfml-db:
    image: postgres:12.4-alpine
    container_name: "mass-pfml-db"
    ports:
      - "5432:5432"
    # Docs for options to the postgres server command:
    # https://www.postgresql.org/docs/current/app-postgres.html
    command: postgres -c "log_lock_waits=on" -N 1000 -c "fsync=off"
    environment:
      - POSTGRES_DB=pfml
      - POSTGRES_USER=pfml
      - POSTGRES_PASSWORD=secret123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - mass-pfml-db
  mass-pfml-api:
    build:
      context: .
      target: dev
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-nodummy}
    image: mass-pfml-api:dev
    container_name: mass-pfml-api
    init: true
    links:
      - mass-pfml-db
    ports:
      - "1550:1550"
    environment:
      # Misc. non-app settings
      - TERM=${TERM:-xterm-256color}
      - 'PS1=${DOCKER_PS1:-[docker] \w: }'
      - 'LSCOLORS=${DOCKER_LSCOLORS:- }'
      - RUN_CMD_OPT=NATIVE
      - ENABLE_FULL_ERROR_LOGS=1
      - PYTHONPATH=/app/
      # Application configuration
      - ENVIRONMENT=local
      - DB_HOST=mass-pfml-db
      - DB_NAME=pfml
      - DB_ADMIN_USERNAME=pfml
      - DB_ADMIN_PASSWORD=secret123
      - DB_USERNAME=pfml_api
      - DB_PASSWORD=secret123
      - DB_NESSUS_PASSWORD=nessussecret123
      - CORS_ORIGINS=http://localhost:3000
      - COGNITO_USER_POOL_KEYS_URL=file:///app/jwks.json
      - DASHBOARD_PASSWORD=secret123
      - LOGGING_LEVEL=massgov.pfml.fineos.fineos_client=DEBUG
      - ENABLE_EMPLOYEE_ENDPOINTS=1
      - FOLDER_PATH=dor_mock
      - FINEOS_FOLDER_PATH=fineos_mock
      # Enable this variable after initial full load
      # - ELIGIBILITY_FEED_MODE=updates
      # Enable this variable to configure /rmv-check
      - RMV_CHECK_BEHAVIOR=fully_mocked
      - RMV_CHECK_MOCK_SUCCESS=1
      # Enable these variables to use a real FINEOS API instead of a mock:
      # - FINEOS_CLIENT_CUSTOMER_API_URL=https://idt-api.masspfml.fineos.com/customerapi/
      # - FINEOS_CLIENT_WSCOMPOSER_API_URL=https://idt-api.masspfml.fineos.com/integration-services/wscomposer/
      # - FINEOS_CLIENT_GROUP_CLIENT_API_URL=https://idt-api.masspfml.fineos.com/groupclientapi/
      # - FINEOS_CLIENT_INTEGRATION_SERVICES_API_URL=https://idt-api.masspfml.fineos.com/integration-services/
      # - FINEOS_CLIENT_OAUTH2_URL=https://idt-api.masspfml.fineos.com/oauth2/token
      # - FINEOS_CLIENT_OAUTH2_CLIENT_ID=...
      # - FINEOS_CLIENT_OAUTH2_CLIENT_SECRET=...
      # - OAUTHLIB_INSECURE_TRANSPORT=1
      # Disable this variable and set the following three variables to use a real Service Now API instead of a mock:
      - ENABLE_MOCK_SERVICE_NOW_CLIENT=1
      # - SERVICE_NOW_BASE_URL=...
      # - SERVICE_NOW_USERNAME=...
      # - SERVICE_NOW_PASSWORD=...
      - PORTAL_BASE_URL=https://paidleave.mass.gov
      - ENABLE_APPLICATION_FRAUD_CHECK=0
      - PAYMENTS_GAX_BIEVNT_EMAIL=
      - PAYMENTS_DFML_BUSINESS_OPERATIONS_EMAIL=
      - PFML_EMAIL_ADDRESS=noreplypfml@mass.gov
      - BOUNCE_FORWARDING_EMAIL_ADDRESS=noreplypfml@mass.gov

    networks:
      main:
        aliases:
          - mass-pfml-api
    depends_on:
      - "mass-pfml-db"

networks:
  main:

volumes:
  pgdata:
