version: "3.4"

services:
  mass-pfml-db:
    image: postgres:11.6-alpine
    container_name: "mass-pfml-db"
    ports:
      - "5432:5432"
    # Docs for options to the postgres server command:
    # https://www.postgresql.org/docs/current/app-postgres.html
    command: postgres -c "log_lock_waits=on" -N 1000
    environment:
      - POSTGRES_DB=pfml
      - POSTGRES_USER=pfml
      - POSTGRES_PASSWORD=secret123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - mass-pfml-db
  mass-pfml-api:
    build:
      context: .
      target: dev
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-nodummy}
    image: mass-pfml-api:dev
    container_name: mass-pfml-api
    links:
      - mass-pfml-db
    ports:
      - "1550:1550"
    # We set `:z` on the bind mounts to support Linux systems with SELinux, on
    # other platforms it has no effect.
    #
    # https://docs.docker.com/storage/bind-mounts/
    volumes:
      # To make local development easier, mount project code so that we don't
      # have to rebuild the docker container every time we run
      - .:/app:z
    environment:
      - ENVIRONMENT=local
      - ENABLE_FULL_ERROR_LOGS=1
      - PYTHONPATH=/app/
      - DB_HOST=mass-pfml-db
      - DB_NAME=pfml
      - DB_USERNAME=pfml
      - DB_PASSWORD=secret123
      - COGNITO_USER_POOL_KEYS_URL=file:///app/jwks.json
      - TERM=${TERM:-xterm-256color}
      - 'PS1=${DOCKER_PS1:-[docker] \w: }'
      - 'LSCOLORS=${DOCKER_LSCOLORS:- }'
      - PY_RUN_CMD_OPT=POETRY
      - ENABLE_EMPLOYEE_ENDPOINTS=1
      - ENABLE_EMPLOYER_ENDPOINTS=1
    networks:
      main:
        aliases:
          - mass-pfml-api
    depends_on:
      - "mass-pfml-db"

networks:
  main:

volumes:
  pgdata:
