version: "3.8"

services:
  sftp:
    image: atmoz/sftp
    container_name: "mass-pfml-sftp"
    ports:
      - "2222:22"
    command: foo:pass:1001
    volumes:
      - ./local_sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./local_sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ./local_sftp/ssh_api_rsa_key.pub:/home/foo/.ssh/keys/ssh_api_rsa_key.pub:ro
      - ./local_sftp/upload:/home/foo/upload
    networks:
      main:
        aliases:
          - mass-pfml-sftp
  mass-pfml-db:
    image: postgres:12.4-alpine
    container_name: "mass-pfml-db"
    platform: linux/amd64 # Fix running on Apple silicon 
    ports:
      - "5432:5432"
    # Docs for options to the postgres server command:
    # https://www.postgresql.org/docs/current/app-postgres.html
    command: postgres -c "log_lock_waits=on" -N 1000 -c "fsync=off"
    environment:
      - POSTGRES_DB=pfml
      - POSTGRES_USER=pfml
      - POSTGRES_PASSWORD=secret123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - mass-pfml-db
  mass-pfml-api:
    build:
      context: .
      target: dev
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-nodummy}
    image: mass-pfml-api:dev
    container_name: mass-pfml-api
    init: true
    links:
      - mass-pfml-db
    platform: linux/amd64 # Fix running on Apple silicon 
    ports:
      - "1550:1550"
    environment:
      # Misc. non-app settings
      - TERM=${TERM:-xterm-256color}
      - 'PS1=${DOCKER_PS1:-[docker] \w: }'
      - 'LSCOLORS=${DOCKER_LSCOLORS:- }'
      - RUN_CMD_OPT=NATIVE
      - ENABLE_FULL_ERROR_LOGS=1
      - PYTHONPATH=/app/
      # Application configuration
      - ENVIRONMENT=local
      - DB_HOST=mass-pfml-db
      - DB_NAME=pfml
      - DB_ADMIN_USERNAME=pfml
      - DB_ADMIN_PASSWORD=secret123
      - DB_USERNAME=pfml_api
      - DB_PASSWORD=secret123
      - DB_NESSUS_PASSWORD=nessussecret123
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
      - COGNITO_USER_POOL_KEYS_URL=${COGNITO_USER_POOL_KEYS_URL:-file:///app/jwks.json}
      # Stage Cognito resource
      - COGNITO_USER_POOL_ID=us-east-1_HpL4XslLg
      - COGNITO_USER_POOL_CLIENT_ID=10rjcp71r8bnk4459c67bn18t8
      - DASHBOARD_PASSWORD=secret123
      - LOGGING_LEVEL=massgov.pfml.fineos.fineos_client=DEBUG,massgov.pfml.servicenow.client=DEBUG
      - ENABLE_EMPLOYEE_ENDPOINTS=1
      - FOLDER_PATH=dor_mock
      - FINEOS_FOLDER_PATH=fineos_mock
      # Enable this variable after initial full load
      # - ELIGIBILITY_FEED_MODE=updates
      # Enable this variable to configure calls to the RMV API
      - RMV_API_BEHAVIOR=fully_mocked
      # Enable this variable to configure /rmv-check
      - RMV_CHECK_MOCK_SUCCESS=1
      # Disable this variable and set the following three variables to use a real Service Now API instead of a mock:
      - ENABLE_MOCK_SERVICE_NOW_CLIENT=1

      - ENABLE_EMPLOYER_REIMBURSEMENT_PAYMENTS=0
      # - SERVICE_NOW_BASE_URL=...
      # - SERVICE_NOW_USERNAME=...
      # - SERVICE_NOW_PASSWORD=...
      - PORTAL_BASE_URL=https://paidleave.mass.gov
      - ENABLE_APPLICATION_FRAUD_CHECK=0
      - ENABLE_DOCUMENT_MULTIPART_UPLOAD=0

      # Payments env vars
      # - PAYMENTS_GAX_BIEVNT_EMAIL=
      # - PAYMENTS_DFML_BUSINESS_OPERATIONS_EMAIL=
      - AGENCY_REDUCTIONS_EMAIL_ADDRESS=EOL-DL-DFML-Agency-Reductions@mass.gov
      - DFML_PROJECT_MANAGER_EMAIL_ADDRESS=
      # Disabled locally so we don't need to authenticate with AWS SES
      - DISABLE_SENDING_EMAILS=1
      - PFML_EMAIL_ADDRESS=PFML_DoNotReply@eol.mass.gov
      - BOUNCE_FORWARDING_EMAIL_ADDRESS=PFML_DoNotReply@eol.mass.gov
      # Uncomment and set these in order to run the FINEOS and CTR ECS tasks locally with real S3
      # You'll also need to configure the mount for your ~/.aws/credentials in
      # docker-compose.override.yml in order for this to work.
      #- FINEOS_DATA_EXPORT_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/fake-fineos-export/
      #- FINEOS_DATA_IMPORT_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/fake-fineos-import/
      #- PFML_CTR_INBOUND_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/ctr/inbound
      #- PFML_CTR_OUTBOUND_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/ctr/outbound
      #- PFML_FINEOS_INBOUND_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/cps/inbound
      #- PFML_FINEOS_OUTBOUND_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/cps/outbound
      #- PFML_ERROR_REPORTS_PATH=s3://massgov-pfml-test-agency-transfer/chouinard-test/payments/error-reports/outbound
      #- AWS_PROFILE=AWS-498823821309-Infrastructure-Admin_profile
      #- NEW_PLAN_PROOFS_ACTIVE_AT=2021-06-26 00:00:00+00:00
      #- FEATURES_FILE_PATH=file:///app/features.yaml
      - PDF_API_HOST=https://mass-pfml-pdf-api
      - ENABLE_GENERATE_1099_PDF=1
      - GENERATE_1099_MAX_FILES=1000
      - ENABLE_MERGE_1099_PDF=1
      - ENABLE_UPLOAD_1099_PDF=1
      - ENABLE_APPLICATION_IMPORT=1
      - UPLOAD_MAX_FILES_TO_FINEOS=10
      - TEST_FILE_GENERATION_1099=0
      - IRS_1099_CORRECTION_IND=0
      - IRS_1099_TAX_YEAR=2021
      - MOVEIT_SFTP_URI=sftp://foo@mass-pfml-sftp:22
      - SFTP_URI=sftp://foo@mass-pfml-sftp:22

    networks:
      main:
        aliases:
          - mass-pfml-api
    depends_on:
      - "mass-pfml-db"

networks:
  main:

volumes:
  pgdata:
