# Run tests and linting for the Admin Portal

name: Admin Portal CI

on:
  push:
    branches:
      - main
    paths:
      - admin/**
  pull_request:
    paths:
      - admin/**

env:
  nodeVersion: 15.x
  working-dir: ./admin

jobs:
  lint_admin_portal:
    name: Lint and Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nodeVersion }}

      - name: install
        run: npm ci
        working-directory: ${{ env.working-dir }}

      - name: format
        run: npm run format-check:ci
        working-directory: ${{ env.working-dir }}

      - name: lint
        run: npm run lint
        working-directory: ${{ env.working-dir }}

      - name: test
        run: npm run test
        working-directory: ${{ env.working-dir }}
  
