# This workflow generates database erds files for the api schema

name: Update API ERD Diagrams

on:
  workflow_dispatch:
    inputs:
    tags:
      description: 'Generate ERD'  
  push:
    branches:
      - main
    paths:
      - api/massgov/pfml/db/models/**
      - api/bin/create-erds.py

defaults:
  run:
    working-directory: ./api

jobs:
  update-erds:
    runs-on: ubuntu-latest
    steps:
      - name: "Create ERDs"
        run: make create-erds

      - uses: EndBug/add-and-commit@v6
        with:
          add: '../docs/assets/api/erds'
          message: 'ERD generation auto-commit'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
