name: Payments Voucher Daily Check
#Daily cron job to ensure the payment voucher file was generated overnight. This should exist until the process is fully automated with PUB.

on:
  workflow_dispatch:
  schedule:
  # scheduled to run weekdays at 7:30 AM ET
    - cron: '30 11 * * MON-FRI'

defaults:
  run:
    working-directory: .

jobs:
  payment-voucher-check:
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PFML_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PFML_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 3600
          role-to-assume: ci-run-deploys
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Check voucher file exists and its size
        id: s3check
        run: |
          voucher_file=$(
            aws s3 sync s3://massgov-pfml-prod-agency-transfer . \
            --exclude "*" --include "payments/manual-payment-voucher/${{ steps.date.outputs.date }}/*_payment_voucher.csv" \
             --dryrun | awk '{print $3}'
             )

          if [ -z $voucher_file ]; then
            echo "Couldn't find a voucher file for today"
            exit 1
          else
            echo "Found a voucher file for current day: $voucher_file"
          fi

          file_size=$(aws s3 ls $voucher_file | awk '{print $3}')
          echo "File size is: $file_size bytes"

          if [ $file_size -gt 1500 ]; then
            echo "File is bigger than 1.5KB, should have data."
          else
            echo "File is smaller than 1.5KB, possibly empty"
            exit 1
          fi

  alert-if-failed:
    runs-on: ubuntu-latest
    needs: [payment-voucher-check]
    if: always() && needs.payment-voucher-check.result == 'failure'
    steps:
    - name: send high priority page if file is missing or empty
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://events.pagerduty.com/v2/enqueue'
        method: 'POST'
        contentType: 'application/json'
        data: "{
          \"routing_key\": \"60e2a861cbe64208c0ae9ddcfa02938e\", 
          \"event_action\": \"trigger\",
          \"dedup_key\":\"payment-voucher-check\",
          \"payload\": {
            \"summary\": \"Payments voucher file missing/empty\",
            \"severity\": \"critical\",
            \"source\": \"Payments Voucher Check\",
            \"custom_details\": {
              \"description\": \"Payments voucher file missing or empty\"
              }
            },
            \"links\": [
              {
              \"href\":\"https://github.com/EOLWD/pfml/actions/runs/${{ github.run_id }}\",
              \"text\": \"GitHub Actions run\"
              }
            ]
          }"
