name: API Migration Conflict Check

on:
  pull_request:
    paths:
      - api/massgov/pfml/db/migrations/versions/**

jobs:
  # Check for no conflicting Alembic migrations
  check-migration-heads:
    runs-on: ubuntu-latest

    env:
      baseref: ${{ github.base_ref }}
      headref: ${{ github.head_ref }}

    steps:
      - uses: actions/checkout@v2

      - name: get migration diff
        run: |
          git fetch origin $baseref $headref
          git diff --diff-filter=D --name-only origin/$baseref origin/$headref -- ./api/massgov/pfml/db/migrations/versions > migrations.log
          if [ -s migrations.log ]; then
            echo "The following migrations are missing, please update your branch with master:"
            cat migrations.log
            exit 1
          else
            echo "No migration conflicts"
            exit 0
          fi
