name: End-to-End Test Suite (Nightly)

on:
  schedule:
    # Kick off a scheduled run at Midnight UTC.
    - cron: '0 0 * * *'

jobs:
  test:
    name: End-To-End Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress Tests
        id: cypress
        uses: cypress-io/github-action@v2
        with:
          spec: "cypress/integration/endtoend/**/*"
          record: true
          working-directory: e2e
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          E2E_API_BASEURL: ${{ secrets.E2E_API_BASEURL }}
          E2E_FINEOS_BASEURL: ${{ secrets.E2E_FINEOS_BASEURL }}
          E2E_FINEOS_USERNAME: ${{ secrets.E2E_FINEOS_USERNAME }}
          E2E_FINEOS_PASSWORD: ${{ secrets.E2E_FINEOS_PASSWORD }}
          E2E_PORTAL_BASEURL: ${{ secrets.E2E_PORTAL_BASEURL }}
          E2E_PORTAL_USERNAME: ${{ secrets.E2E_PORTAL_USERNAME }}
          E2E_PORTAL_PASSWORD: ${{ secrets.E2E_PORTAL_PASSWORD }}
          E2E_TESTMAIL_APIKEY: ${{ secrets.E2E_TESTMAIL_APIKEY }}
          E2E_TESTMAIL_NAMESPACE: ${{ secrets.E2E_TESTMAIL_NAMESPACE }}
          # passing token to detect a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Upload artifacts to capture the run as well.
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Cypress-Videos
          path: cypress/videos/*
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Cypress-Screenshots
          path: cypress/screenshots/*
      - name: Print Dashboard URL
        if: always()
        run: |
          echo Cypress finished with: ${{ steps.cypress.outcome }}
          echo See results at ${{ steps.cypress.outputs.dashboardUrl }}

