name: ECR Repository Scan

on:
  workflow_dispatch:
  schedule:
  # scheduled to run every Monday morning at 4am
    - cron: '0 4 * * 1'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PFML_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PFML_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ci-run-deploys
          role-duration-seconds: 3600      
      
      - name: Install boto3
        run: pip install boto3

      - name: Install botocore
        run: pip install botocore
         
      - name: start ECR scan
        run: python ecr_repo_scan.py 
        working-directory: ./api/bin/