# Run tests and linting for the Portal
#
name: Portal CI

on:
  push:
    branches:
      - main
    paths:
      - portal/**
      - .github/workflows/portal-ci.yml
  pull_request:
    paths:
      - portal/**
      - .github/workflows/portal-ci.yml

concurrency:
  group: ${{ github.head_ref }}-ci
  cancel-in-progress: true

  # TODO(kevin): Not sure if this ignores concurrency cancellations
  post-to-slack:
    name: Post failures to slack
    if: failure() && github.ref == 'refs/heads/main'
    uses: EOLWD/pfml/.github/workflows/reusable-send-slack-message.yml@kev/fix-ci-notifications
    with:
      title: "[main] Portal tests failed (<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|build logs>)"
      color: danger