# Run tests and linting for the Paid Leave website
#
  name: Portal Website Testing

  on:
    pull_request:
      paths:
      - portal/**
      - infra/portal/config/**

  env:
    nodeVersion: 12.x

  jobs:
    lint:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nodeVersion }}

      - name: install
        run:
          npm ci

      - name: lint
        run:
          npm run lint

    test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nodeVersion }}

      - name: install
        run:
          npm ci --prefix portal

      - name: test
        run:
          npm run test:no-coverage --prefix portal

    test-cov:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nodeVersion }}

      - name: install
        run:
          npm ci --prefix portal

      - name: test-cov
        run:
          npm test --prefix portal
    
    storybook:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nodeVersion }}

      - name: install
        run:
          npm ci --prefix portal

      - name: Smoke test Storybook
        run: npm run docs:smoke-test --prefix portal
