# Run tests and linting for the Portal
#
name: Portal CI

on:
  pull_request:
    paths:
      - portal/**

env:
  nodeVersion: 12.x

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nodeVersion }}

      - name: install
        run: npm ci

      - name: lint
        run: npm run lint:ci

  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nodeVersion }}

      - name: install
        run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci --prefix portal

      - name: test
        run: npm test --prefix portal

  test-e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nodeVersion }}

      - name: install
        run: npm ci --prefix portal

      - name: Headless browser tests
        run: npm run test:e2e:ci --prefix portal
