  name: Portal Testing

  on:
    pull_request:
      paths:
      - 'portal/**'

  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: install
        run:
          npm ci --prefix portal

      - name: test
        run:
          npm test --prefix portal
