name: Pull Request title linter

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        shell: python
        run: |
          import os
          import re
          import sys

          TITLE_RE = re.compile(r"[A-Z]+-\d+:")

          title = os.environ["TITLE"]

          print(sys.version)
          print("PR title: %r" % title)

          if TITLE_RE.match(title):
              pass
          else:
              print("::error file=docs/contributing.md,line=1,title=Invalid PR title::Please start the PR title with a JIRA ticket, e.g. AAA-123: ...")
              raise RuntimeError("PR title must start with JIRA ticket")
