name: Pull Request title linter

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        shell: python
        run: |
          import re
          import sys

          TITLE_RE = re.compile(r"[A-Z]+-\d+:")

          title = "${{ github.event.pull_request.title }}"

          print(sys.version)
          print("PR title: %r" % title)

          if TITLE_RE.match(title):
              pass
          else:
              raise RuntimeError("PR title must start with JIRA ticket")
