#
# GitHub action to check each pull request follows our preferred format.
#

name: Pull request format linter

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_title_and_body:
    name: Check title and body
    runs-on: ubuntu-latest
    steps:
      - name: Check title and body
        env:
          TITLE: ${{ github.event.pull_request.title }}
          BODY: ${{ github.event.pull_request.body }}
          STATE: ${{ github.event.pull_request.state }}
        shell: python
        run: |
          import os
          import re
          import sys

          title = os.environ["TITLE"]
          body = os.environ["BODY"]
          state = os.environ["STATE"]

          problem_count = 0

          if not re.match(r"[A-Z]+-\d+:", title):
              print("::error title=PR title doesn't start with a ticket::"
                    "Please start the PR title with a JIRA ticket, "
                    "for example \"AAA-123: /summary/\"")
              problem_count += 1

          if not re.search(r"https://lwd.atlassian.net/browse/[A-Z]+-\d+", body):
              print("::error title=PR description doesn't link to a ticket::"
                    "Please include a JIRA ticket link in the PR description, "
                    "for example https://lwd.atlassian.net/browse/AAA-123")
              problem_count += 1
