name: ZZ-testing-git-to-teams
on:
  workflow_dispatch:
  push:
    branches:
      - INFRA-1113--Testing-Github-to-Teams

jobs:

  # Run Terriyay
  post-to-teams:
    name: post failures to teams


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PFML_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PFML_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ci-run-deploys
          role-duration-seconds: 3600

      - name: Pull teams uri from SSM
        uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "/admin/common/teams-deploy-uri-test"
          env_variable_name: "teams_uri"
        
      - name: display teams uri
        run: |
          echo ${{ env.teams_uri }}


      - name: Post to Teams
        run: |
          RESPONSE=$(curl -fsLS -X POST ${{ env.TEAMS_URI }} \
          --header 'Content-Type: application/json' \
          --data '{   
            "@type": "MessageCard",
            "themeColor": "FF0000",
            "title": "API tests failed",
            "text": "API tests failed in main ${{ env.workflow_self_link }}",
            )
