# Lint checker for the github/workflows YAML files that are adjusted.
#
name: Actionlint GHA Workflows

on:
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  lint:
    name: Actionlint GHA Workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: actionlint checker
        # We are disabling the shellcheck (-shellcheck=) from running for the moment.
        # Also ignoring two errors pertaining to reusable workflows, which will be resolved by these upstream PRs:
        #   https://github.com/rhysd/actionlint/pull/107
        #   https://github.com/rhysd/actionlint/pull/106
        run: ${{ steps.get_actionlint.outputs.executable }} -color --ignore "reusable workflow call .* is not following the format" --ignore 'property "github_token" is not defined in object type' -shellcheck=
        shell: bash
